apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferenceservice.ome.oracle.com
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: ome-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-inferenceservices
    failurePolicy: Fail
    name: inferenceservice.ome-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - ome.oracle.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices