@startuml

package "Inference Service" {
  object InferenceService {
    + InferenceServiceSpec spec
    + InferenceServiceStatus status
  }

  object InferenceServiceSpec {
    + PredictorSpec predictor
    + string compartmentID
    + KedaConfig kedaConfig
  }

  object PredictorSpec {
    + ModelSpec model
    + PodSpec podSpec
    + ComponentExtensionSpec componentExtension
    + WorkerSpec workerSpec
  }

  object WorkerSpec {
    + PodSpec podSpec
    + int worldSize
  }

  object ModelSpec {
    + string runtime
    + PredictorExtensionSpec predictorExtension
    + string baseModel
    + string[] fineTunedWeights
  }

  object PredictorExtensionSpec {
    + string storageUri
    + string runtimeVersion
    + InferenceServiceProtocol protocolVersion
    + Container container
  }

  object PodSpec {
    + Container[] containers
    + Volume[] volumes
    + NodeSelector nodeSelector
    + Affinity affinity
    + Tolerations[] tolerations
    + Labels labels
    + Annotations annotations
    + ImagePullSecrets[] imagePullSecrets
  }

  object ComponentExtensionSpec {
    + int minReplica
    + int maxReplica
    + int scalerTarget
    + ScalerMetrics scalerMetrics
    + int64 containerConcurrency
    + int64 timeoutSeconds
    + int64 canaryTrafficPercent
    + LoggerSpec logger
    + map[string]string labels
    + map[string]string annotations
    + DeploymentStrategy deploymentStrategy
  }

  object LoggerSpec {
    + string URL
    + LoggerType mode
  }

  enum LoggerType {
    + all
    + request
    + response
  }

  enum InferenceServiceProtocol {
    + openAI
    + cohere
    + openInferenceProtocolV1
    + openInferenceProtocolV2
  }

  object ScalerMetrics {
    + string cpu
    + string memory
    + string rps
    + string concurrency
  }

  InferenceService --> InferenceServiceSpec
  InferenceServiceSpec --> PredictorSpec
  PredictorSpec --> ModelSpec
  PredictorSpec --> PodSpec
  PredictorSpec --> ComponentExtensionSpec
  PredictorSpec --> WorkerSpec
  ModelSpec --> PredictorExtensionSpec
  PredictorExtensionSpec --> InferenceServiceProtocol
  ComponentExtensionSpec --> ScalerMetrics
  ComponentExtensionSpec --> LoggerSpec
  LoggerSpec --> LoggerType
}

package InferenceServiceStatus {
  object InferenceServiceStatus {
    + duckv1.Status status
    + duckv1.Addressable address
    + apis.URL url
    + map[ComponentType]ComponentStatusSpec components
    + ModelStatus modelStatus
  }

  object ComponentStatusSpec {
    + string latestReadyRevision
    + string latestCreatedRevision
    + string previousRolledoutRevision
    + string latestRolledoutRevision
    + []knservingv1.TrafficTarget traffic
    + apis.URL url
    + apis.URL restUrl
    + duckv1.Addressable address
  }

  object ModelStatus {
    + TransitionStatus transitionStatus
    + ModelRevisionStates states
    + FailureInfo lastFailureInfo
    + ModelCopies copies
  }

  enum TransitionStatus {
    + UpToDate
    + InProgress
    + BlockedByFailedLoad
    + InvalidSpec
  }

  object FailureInfo {
    + string location
    + FailureReason reason
    + string message
    + string ModelRevisionName
    + Time time
    + int32 exitCode
  }

  enum FailureReason {
    + ModelLoadFailed
    + RuntimeUnhealthy
    + RuntimeDisabled
    + NoSupportingRuntime
    + RuntimeNotRecognized
    + InvalidPredictorSpec
    + BaseModelNotFound
    + BaseModelDisabled
    + FineTunedWeightNotFound
    + BaseModelDeprecated
    + FineTunedWeightDeprecated
    + FineTuneWeightLoadFailed
  }

  object ModelRevisionStates {
    + ModelState activeModelState
    + ModelState targetModelState
  }

  enum ModelState {
    + Pending
    + Standby
    + Loading
    + Loaded
    + FailedToLoad
  }

  object ModelCopies {
    + int failedCopies
    + int totalCopies
  }

  InferenceServiceStatus --> ComponentStatusSpec
  InferenceServiceStatus --> ModelStatus
  ModelStatus --> ModelRevisionStates
  ModelStatus --> FailureInfo
  ModelStatus --> TransitionStatus
  ModelStatus --> ModelCopies
  FailureInfo --> FailureReason
  ModelRevisionStates --> ModelState
}
@enduml
