@startuml
package "Base Model" {
  object ClusterBaseModel {
    + BaseModelSpec spec
    + ModelStatus status
  }
  object BaseModel {
    + BaseModelSpec spec
    + ModelStatus status
  }

  object BaseModelSpec {
    + ModelFormat modelFormat
    + string modelType
    + string modelArchitecture
    + string modelParameterSize
    + ModelCapabilities[] modelCapabilities
    + json modelConfiguration
    + json tensorRTLLMConfiguration
    + Storage storage
    + ModelExtension modelExtension
    + ServingMode[] servingMode
  }

  enum ServingMode {
    + OnDemand
    + Dedicated
  }

  object ModelFormat {
    + string name
    + string version
  }

  enum ModelCapabilities {
    + TextGeneration
    + TextSummarization
    + TextEmbedding
    + TextRerank
    + Chat
    + Vision
    + Unknown
  }

  enum LifecycleState {
    + Creating
    + Importing
    + InTransit
    + InTraining
    + Ready
    + Failed
  }

  enum Lifecycle {
    + Deprecated
    + Experimental
    + Public
    + Internal
  }

  object Storage {
    + string path
    + string schemaPath
    + map<string, string> parameters
    + string storageKey
  }

  object ModelExtension {
    + string version
    + bool disabled
    + string vendor
    + string compartmentID
  }

  object ModelStatus {
    + Lifecycle lifecycle
    + LifecycleState state
  }

  ClusterBaseModel --> BaseModelSpec
  BaseModel --> BaseModelSpec
  BaseModelSpec --> ModelFormat
  BaseModelSpec --> ModelCapabilities
  BaseModelSpec --> ServingMode
  BaseModelSpec --> Storage
  BaseModelSpec --> ModelExtension
  ClusterBaseModel --> ModelStatus
  BaseModel --> ModelStatus
  ModelStatus --> Lifecycle
  ModelStatus --> LifecycleState
}

package "Fine-Tuned Weight" {
  object FineTunedWeight {
    + ObjectReference baseModelRef
    + string modelType
    + json hyperParameters
    + ModelExtension modelExtension
    + Storage storage
    + ModelStatus status
  }

  object ObjectReference {
    + string name
    + string namespace
  }

  FineTunedWeight --> ObjectReference
  FineTunedWeight --> Storage
  FineTunedWeight --> ModelExtension
  FineTunedWeight --> ModelStatus
}
@enduml