@startuml
package "Serving Runtime" {

  object ClusterServingRuntime {
    + ServingRuntimeSpec spec
    + ServingRuntimeStatus status
  }

  object ServingRuntime {
    + ServingRuntimeSpec spec
    + ServingRuntimeStatus status
  }

  object ServingRuntimeSpec {
    + SupportedModelFormat[] supportedModels
    + bool disabled
    + InferenceServiceProtocol[] protocolVersions
    + ServingRuntimePodSpec servingRuntimePodSpec
    + string httpDataEndpoint
    + uint16 replicas
    + BuiltInAdapter builtInAdapter
    + string compartmentID
  }

  enum InferenceServiceProtocol {
    + openInference-v1
    + openInference-v2
    + openAI
    + cohere
  }

  object SupportedModelFormat {
    + string name
    + string version
    + string modelArchitecture
    + string modelType
    + bool autoSelect
    + int32 priority
  }

  object ServingRuntimePodSpec {
    + Container[] containers
    + Volume[] volumes
    + NodeSelector nodeSelector
    + Affinity affinity
    + Tolerations[] tolerations
    + Labels labels
    + Annotations annotations
    + ImagePullSecrets[] imagePullSecrets
  }

  object BuiltInAdapter {
    + ServerType serverType
    + int modelLoadingTimeoutMillis
    + EnvVar[] env
  }

  enum ServerType {
    + triton
    + vllm
    + tgi
    + cohere
    + nim
  }

  object ServingRuntimeStatus {
    + string status
    + LifecycleState state
  }

  enum LifecycleState {
    + Creating
    + Ready
    + Failed
  }

  ClusterServingRuntime --> ServingRuntimeSpec
  ServingRuntime --> ServingRuntimeSpec
  ClusterServingRuntime --> ServingRuntimeStatus
  ServingRuntime --> ServingRuntimeStatus
  ServingRuntimeSpec --> InferenceServiceProtocol
  ServingRuntimeSpec --> SupportedModelFormat
  ServingRuntimeSpec --> ServingRuntimePodSpec
  ServingRuntimeSpec --> BuiltInAdapter
  BuiltInAdapter --> ServerType
  ServingRuntimeStatus --> LifecycleState
}

@enduml
