@startuml ServingRuntime

package "Serving Runtime" {

  object ClusterServingRuntime {
    + ServingRuntimeSpec spec
    + ServingRuntimeStatus status
  }

  object ServingRuntime {
    + ServingRuntimeSpec spec
    + ServingRuntimeStatus status
  }

  object ServingRuntimeSpec {
    + SupportedModelFormat[] supportedModels
    + bool disabled
    + string[] protocolVersions
    + PodSpec podSpec
    + string httpDataEndpoint
    + uint16 replicas
    + BuiltInAdapter builtInAdapter
    + string compartmentID
    + ResourceRequirements resourceRequirements
    + ModelScheduler modelScheduler
    + AccumulateSteps accumulateSteps
    + bool keepAlive
    + bool optimizeForInference
    + string[] tags
  }

  object PodSpec {
    + Container[] containers
    + Volume[] volumes
    + NodeSelector nodeSelector
    + Affinity affinity
    + Tolerations[] tolerations
    + Labels labels
    + Annotations annotations
    + ImagePullSecrets[] imagePullSecrets
    + ServiceAccountName serviceAccountName
  }

  object SupportedModelFormat {
    + string name
    + string version
    + string modelArchitecture
    + string framework
    + string[] modelTypes
    + bool autoSelect
    + int32 priority
    + string quantization
    + string[] modelCapabilities
  }

  object BuiltInAdapter {
    + ServerType serverType
    + int modelLoadingTimeoutMillis
    + EnvVar[] env
    + json serverConfig
  }

  object ResourceRequirements {
    + ResourceList requests
    + ResourceList limits
  }

  object ModelScheduler {
    + string type
    + int defaultBatchSize
    + int maxBatchSize
    + int batchingWindow
  }

  object AccumulateSteps {
    + bool enabled
    + int numSteps
    + int sequenceLength
  }

  enum ServerType {
    + triton
    + vllm
    + tgi
    + cohere
    + nim
    + llama_cpp
    + tensorrt_llm
  }

  object ServingRuntimeStatus {
    + string status
    + LifecycleState state
    + Condition[] conditions
    + Time lastUpdateTime 
  }

  enum LifecycleState {
    + Creating
    + Ready
    + Failed
  }

  ClusterServingRuntime --|> ServingRuntimeSpec
  ServingRuntime --|> ServingRuntimeSpec
  ClusterServingRuntime --|> ServingRuntimeStatus
  ServingRuntime --|> ServingRuntimeStatus
  ServingRuntimeSpec --> SupportedModelFormat
  ServingRuntimeSpec --> PodSpec
  ServingRuntimeSpec --> BuiltInAdapter
  ServingRuntimeSpec --> ResourceRequirements
  ServingRuntimeSpec --> ModelScheduler
  ServingRuntimeSpec --> AccumulateSteps
  BuiltInAdapter --> ServerType
  ServingRuntimeStatus --> LifecycleState
}

@enduml
