auth_type: &default_auth_type "UserPrincipal"
profile: "DEFAULT"
region: "eu-frankfurt-1"

local_path: "/Users/simolin/mnt/cohere/command-r-v1.6-16k"
model_store_directory: "/opt/ml/model"
model_name: "command-r-v1.6-16k"
hf_token: "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"
skip_sha: false
max_retries: 5
retry_internal_in_seconds: 10
num_connections: 100

download_size_limit_gb: 650
enable_size_limit_check: true

source:
  bucket_name: "partner-models"
  prefix: "cohere/command-r-v1.6-16k/"
  region: "us-chicago-1"
  namespace: "idqj093njucb"

target:
  bucket_name: "simolin-test-bucket"
  prefix: "cohere/command-r-v1.6-16k/"
  region: "eu-frankfurt-1"
  namespace: "idqj093njucb"

model_framework: tensorrtllm
tensorrt_llm_version: "v0.11.0"
node_shape_alias: ""
num_of_gpu: 1
disable_model_decryption: false

compartment_id: "ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva"
vault_id: "ocid1.vault.oc1.us-chicago-1.ijsr6afaaagp2.abxxeljtatzowkwlt2iu42ndlmnmd4d4nausgoubu7uq7iro553xdj5b6weq"
key_name: "command_r"
secret_name: "command_r-dek"
model_type: "Serving"

# Configs for serving sidecar
finetuned_model_info_file_path: "/mnt/ft-model-info.json"
unzipped_finetuned_model_directory: "/mnt/unzipped-ft-models"
zipped_finetuned_model_directory: "/mnt/zipped-ft-models"

# Configs for training agent
runtime: "cohere" #cohere, cohere-commandr, peft
training_name: &training_name "amaaaaaalqj567aahdgokyhrpfmgd374so3n54necmdq7iyod2aye3yfv2yq"
model_directory: "/mnt/cohere/amaaaaaalqj567aahdgokyhrpfmgd374so3n54necmdq7iyod2aye3yfv2yq"
input_object_store:
  enable_obo_token: true
  obo_token: ""
training_data:
  bucket_name: ""
  namespace: ""
  object_name: ""
model:
  bucket_name: "fine-tuned-model-weights"
  namespace: &service_tenancy_namespace "idqj093njucb"
  object_name: *training_name
training_metrics:
  bucket_name: "model-training-metrics"
  namespace: *service_tenancy_namespace
  object_name: *training_name
cohere_ft:
  name:                       *training_name
  size:                       "6b"
  strategy:                   "tfew"
  serving_strategy:           ""
  train_epochs:               3
  learning_rate:              0.001
  train_batch_size:           32
  early_stopping_patience:    5
  early_stopping_threshold:   0.001
  log_train_status_every_steps: 0
  n_last_layers:              0
  tensor_parallel_size:       0
  base_model:                 ""
  lora_config:
    rank: 0
    alpha: 0
peft_ft:
  model_name: "Llama-2-70b-chat-hf"
  train_dataset_file: "training_data.jsonl"
  num_train_epochs: 3
  learning_rate: 0.002
  train_batch_size: 8
  early_stopping_patience: 15
  early_stopping_threshold: 0.0001
  log_model_metrics_interval_in_steps: 10
  peft_type: "lora"
  lora_r: 8
  lora_alpha: 8
  lora_dropout: 0.1