auth_type: &default_auth_type "UserPrincipal"
profile: "DEFAULT"

local_path: "/Users/simolin/mnt/cohere/command-r-v1.6-16k"
model_name: "command-r-v1.6-16k"
hf_token: "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"
skip_sha: false
max_retries: 5
retry_internal_in_seconds: 10
num_connections: 100

download_size_limit_gb: 650
enable_size_limit_check: true

source:
  bucket_name: "partner-models"
  prefix: "cohere/command-r-v1.6-16k/"
  region: "us-chicago-1"
  namespace: "idqj093njucb"

target:
  bucket_name: "simolin-test-bucket"
  prefix: "cohere/command-r-v1.6-16k/"
  region: "eu-frankfurt-1"
  namespace: "idqj093njucb"

model_framework: tensorrtllm
tensorrt_llm_version: "v0.11.0"
#A10, A100-80GB, A100-40GB, A100-80GB, H100
node_shape_alias: "H100"
num_of_gpu: 1
disable_model_decryption: false

compartment_id: "ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva"
vault_id: "ocid1.vault.oc1.us-chicago-1.ijsr6afaaagp2.abxxeljtatzowkwlt2iu42ndlmnmd4d4nausgoubu7uq7iro553xdj5b6weq"
key_name: "command_r"
secret_name: "command_r-dek"
