package raycluster

import (
	"context"
	"fmt"
	"k8s.io/apimachinery/pkg/api/equality"

	"bitbucket.oci.oraclecorp.com/gen/ome/pkg/apis/serving/v1beta1"
	"bitbucket.oci.oraclecorp.com/gen/ome/pkg/constants"
	ray "github.com/ray-project/kuberay/ray-operator/apis/ray/v1"
	corev1 "k8s.io/api/core/v1"
	apierr "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/util/retry"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

var log = logf.Log.WithName("RayClusterReconciler")

type RayReconciler struct {
	client       client.Client
	scheme       *runtime.Scheme
	RayCluster   *ray.RayCluster
	componentExt *v1beta1.ComponentExtensionSpec
}

func NewRayReconciler(client client.Client,
	scheme *runtime.Scheme,
	componentMeta metav1.ObjectMeta,
	componentExt *v1beta1.ComponentExtensionSpec,
	podSpec *corev1.PodSpec) *RayReconciler {
	return &RayReconciler{
		client:       client,
		scheme:       scheme,
		RayCluster:   createRayCluster(componentMeta, componentExt, podSpec),
		componentExt: componentExt,
	}
}

func createRayCluster(meta metav1.ObjectMeta, ext *v1beta1.ComponentExtensionSpec, spec *corev1.PodSpec) *ray.RayCluster {
	annotations := meta.GetAnnotations()

	// Set default values for RayCluster
	if ext.MinReplicas == nil {
		annotations[constants.MinScaleAnnotationKey] = fmt.Sprint(constants.DefaultMinReplicas)
	} else {
		annotations[constants.MinScaleAnnotationKey] = fmt.Sprint(*ext.MinReplicas)
	}

	if ext.MaxReplicas != 0 {
		annotations[constants.MaxScaleAnnotationKey] = fmt.Sprint(ext.MaxReplicas)
	}

	workerReplicas := int32(*ext.MinReplicas - 1)

	// Modify the worker pod spec for container command and args
	workerPodSpec := spec.DeepCopy()
	for i := range workerPodSpec.Containers {
		workerPodSpec.Containers[i].Command = []string{"/bin/bash", "-lc", "--"}
		workerPodSpec.Containers[i].Args = []string{"ulimit -n 65536; echo worker; $KUBERAY_GEN_RAY_START_CMD"}
	}
	// Create RayCluster object
	rayCluster := &ray.RayCluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:        meta.Name,
			Namespace:   meta.Namespace,
			Labels:      meta.Labels,
			Annotations: annotations,
		},
		Spec: ray.RayClusterSpec{
			HeadGroupSpec: ray.HeadGroupSpec{
				HeadService: &corev1.Service{
					ObjectMeta: metav1.ObjectMeta{
						Name:        meta.Name,
						Namespace:   meta.Namespace,
						Labels:      meta.Labels,
						Annotations: annotations,
					},
				},
				RayStartParams: map[string]string{},
				ServiceType:    corev1.ServiceTypeClusterIP,
				Template: corev1.PodTemplateSpec{
					Spec: *spec,
				},
			},
			WorkerGroupSpecs: []ray.WorkerGroupSpec{
				{
					GroupName:      "worker-group",
					RayStartParams: map[string]string{},
					Replicas:       &workerReplicas,
					Template: corev1.PodTemplateSpec{
						Spec: *workerPodSpec,
					},
				},
			},
		},
	}
	return rayCluster
}

func (r *RayReconciler) Reconcile() (*ray.RayCluster, error) {
	desired := r.RayCluster
	existing := &ray.RayCluster{}

	err := retry.RetryOnConflict(retry.DefaultBackoff, func() error {
		log.Info("Updating Ray cluster", "namespace", desired.Namespace, "name", desired.Name)
		if err := r.client.Get(context.TODO(), types.NamespacedName{Name: desired.Name, Namespace: desired.Namespace}, existing); err != nil {
			return err
		}

		// Set ResourceVersion, which is required for update operation.
		desired.ResourceVersion = existing.ResourceVersion

		// Do a dry-run update to avoid diffs generated by default values introduced by Ray's defaulter webhook.
		if err := r.client.Update(context.TODO(), desired, client.DryRunAll); err != nil {
			// log only if it is not resource conflict error to avoid spamming
			if !apierr.IsConflict(err) {
				log.Error(err, "Failed to perform dry-run update of Ray cluster", "cluster", desired.Name)
			}
			return err
		}
		if err := reconcileRayCluster(desired, existing); err != nil {
			return err
		}
		return r.client.Update(context.TODO(), existing)
	})
	if err != nil {
		// Create a cluster if it does not exist
		if apierr.IsNotFound(err) {
			log.Info("Creating Ray cluster", "namespace", desired.Namespace, "name", desired.Name)
			return desired, r.client.Create(context.TODO(), desired)
		}
		return existing, err
	}
	return existing, nil
}

func reconcileRayCluster(desired *ray.RayCluster, existing *ray.RayCluster) error {
	// Return if no differences to reconcile.
	if semanticEquals(desired, existing) {
		return nil
	}

	// Reconcile differences and update
	existing.Spec = desired.Spec
	existing.ObjectMeta.Labels = desired.ObjectMeta.Labels
	existing.ObjectMeta.Annotations = desired.ObjectMeta.Annotations
	return nil
}

func semanticEquals(desiredCluster, cluster *ray.RayCluster) bool {
	return equality.Semantic.DeepEqual(desiredCluster.Spec, cluster.Spec) &&
		equality.Semantic.DeepEqual(desiredCluster.ObjectMeta.Labels, cluster.ObjectMeta.Labels) &&
		equality.Semantic.DeepEqual(desiredCluster.ObjectMeta.Annotations, cluster.ObjectMeta.Annotations)
}
