runnerTag: latest
name: ome
team: GenAI
phoneBookId: ocasgs
description: Generative AI
majorversion: 1
minorversion: 0
shortversion: ${majorversion}.${minorversion}
version: v${shortversion}-${BLD_NUMBER}${?BLD_BRANCH_SUFFIX}
snapshotVersion: ${shortversion}-SNAPSHOT
releaseBranches: ["main", "hotfix/*"]
triggerOnCommitBranches:  ["main", "pull-requests", "hotfix/*"]
authCompartmentOcid: ocid1.tenancy.oc1..aaaaaaaakyvertmo4tineubnzxftatozvqmdh6anb3bplvdqgsg3y63ctzjq
bitbucketTag: {"enabled": true, "tagName": ${version}, "description": "OME Release Tag"}
shepherd_release_helm_repo: shepherd-release-helm-local

steps:
  [
    {
      name: compilesource
      type: maven
      javaVersion: jdk-17
      mavenCommands: [
        { goal: "validate", args: "-f java-client/pom.xml -N -DrequireVersion="${snapshotVersion} },
        { goal: "versions:set", args: "-f java-client/pom.xml -DnewVersion="${version}" -DprocessAllModules=true" },
        { goal: "verify -f java-client/pom.xml" }
      ]
      artifacts: [
        "**"
      ]
    },
    {
      name: publish_ome_fabric8_java_client_maven_artifacts
      type: publishmaven
      dependsOn: compilesource
      pomLocation: java-client
      repository: ocas-service-platform-release-maven-local
    },
    {
       name: dockerize-manager
       type: dockerizer
       dockerFile: "dockerfiles/manager.Dockerfile"
       dockerBuildPwd: "./"
       images: [
           {
               platform: linux/amd64
           }
       ]
    },
    {
        name: publish_ome_manager_image
        type: publishdocker
        dependsOn: dockerize-manager
        repository: odo-docker-signed-local
        imageName: genai-ome-manager
    }
  ]
