{{- if index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mistral-7b-v0-2-finetuned-model-thought-v0-1
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: "vllm-xsmall-text-generation"
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "isExperimental" }}"
    models.ome.io/internal: "{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "isInternal" }}"
    models.ome.io/lifecycle-phase: "{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "lifecyclePhase" }}"
spec:
  compartmentID: {{ .Values.compartmentID }}
  disabled: false
  displayName: olm.mistral-7b-instruct-v0.2-ft-thought-v0.1
  storage:
    path: "oci://n/{{ .Values.osnamespace }}/b/{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "osBucket" }}/o/{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "vendor" }}/{{ index .Values "mistral-7b-v0-2-finetuned-model-thought-v0-1" "osPrefixOverride" }}"
    storageUri: /mnt/data/models/olm/action-mistral-7b-v0.2-finetuned-model-v0.1
  vendor: olm
  version: "0.1"
  modelFormat:
    name: safetensors
    version: "1"
  modelType: transformer
  modelArchitecture: MistralForCausalLM
  modelParameterSize: 7B
  modelCapabilities:
    - "CHAT"
  maxTokens: 32768
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: SMALL_GENERIC_V2
          quotaUnit: 1
          default: true
{{- end }}