# This runtime is for llama-3-3-70b-instruct, although all the parameters are the same as llama-3-1-70b-instruct
# adding this for the sake of completeness and clarity \_(ツ)_/¯ \_(ツ)_/¯ \_(ツ)_/¯ \_(ツ)_/¯ \_(ツ)_/¯
# five \_(ツ)_/¯ is too much? dont make me add more
# so we don't hear complains about "WHERE IS THE Llama-3-3-70b-instruct"
apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: vllm-llama-3-3-70b-instruct
spec:
  acceleratorRequirements:
    acceleratorClasses:
      - nvidia-a100-80gb-4
      - nvidia-a100-80gb-1
      - nvidia-a100-80gb-2
      - nvidia-a100-80gb-8
      - nvidia-a100-40gb-1
      - nvidia-a100-40gb-2
      - nvidia-a100-40gb-4
      - nvidia-a100-40gb-8
      - nvidia-h100-1
      - nvidia-h100-2
      - nvidia-h100-4
      - nvidia-h100-8
      - nvidia-a10-1
      - nvidia-a10-2
      - nvidia-a10-4
      - nvidia-h200-1
      - nvidia-h200-2
      - nvidia-h200-4
      - nvidia-h200-8
  disabled: false
  {{- if or .Values.commonAnnotations .Values.llama_3_3_70b_instruct.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.llama_3_3_70b_instruct.annotations }}
    {{ toYaml .Values.llama_3_3_70b_instruct.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonLabels .Values.llama_3_3_70b_instruct.labels }}
  labels:
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.llama_3_3_70b_instruct.labels }}
    {{ toYaml .Values.llama_3_3_70b_instruct.labels | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonTolerations .Values.llama_3_3_70b_instruct.tolerations }}
  tolerations:
    {{- if .Values.commonTolerations }}
    {{ toYaml .Values.commonTolerations | nindent 4 }}
    {{- end }}
    {{- if .Values.llama_3_3_70b_instruct.tolerations }}
    {{ toYaml .Values.llama_3_3_70b_instruct.tolerations | nindent 4 }}
    {{- end }}
  {{- end }}
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    {{- if or (eq .Values.oci.realm "oc5") (eq .Values.oci.realm "oc6") }}
    - name: etc-pki
      hostPath:
        path: /etc/pki
        type: Directory
    {{- end }}
  {{ with .Values.llama_3_3_70b_instruct }}
  affinity: {{ .affinity | toYaml | nindent 4 }}
  {{ end }}
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.47.0.dev0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: LlamaForCausalLM
      autoSelect: true
      priority: 1
      version: "1.0.0"
      acceleratorConfig:
        nvidia-a100-80gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-80gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-80gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-80gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a100-40gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-40gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-40gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-40gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-h100-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h100-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h100-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h100-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a10-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a10-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a10-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h200-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h200-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
    - modelFramework:
        name: transformers
        version: "4.47.1"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: LlamaForCausalLM
      autoSelect: true
      priority: 1
      version: "1.0.0"
      acceleratorConfig:
        nvidia-a100-80gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-80gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-80gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-80gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a100-40gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-40gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-40gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-40gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-h100-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h100-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h100-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h100-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a10-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a10-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a10-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h200-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h200-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
    - modelFramework:
        name: transformers
        version: "4.47.1"
      quantization: compressed-tensors
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: LlamaForCausalLM
      autoSelect: false
      priority: 1
      version: "1.0.0"
      acceleratorConfig:
        nvidia-a100-80gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-80gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-80gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-80gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a100-40gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-40gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-40gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-40gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-h100-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h100-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h100-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h100-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a10-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a10-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a10-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h200-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h200-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
  modelSizeRange:
    min: 60B
    max: 75B
  protocolVersions:
    - openAI
  schedulerName: {{ .Values.commonSchedulerName }}
  {{- $gpus := 4 }}
  {{- if eq .Values.oci.region "me-dubai-1" }}{{- $gpus = 8 }}{{- end }}
  containers:
    - name: ome-container
      image: {{ .Values.llama_3_3_70b_instruct.image.vllm.repository | default .Values.vllm.commonImage.repository }}:{{ .Values.llama_3_3_70b_instruct.image.vllm.tag | default .Values.vllm.latestImage.tag }}
      ports:
        - containerPort: {{ .Values.vllm.port }}
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          vllm serve "$MODEL_PATH" \
          --port={{ .Values.vllm.port }} \
          --max-log-len=0 \
          --served-model-name="$SERVED_MODEL_NAME" \
          --tensor-parallel-size={{ $gpus }} \
          --max-model-len=131072 \
          --gpu-memory-utilization=0.9 \
          --enable-chunked-prefill \
          --enable-auto-tool-choice \
          --tool-call-parser=llama3_json \
          --chat-template=./examples/tool_chat_template_llama3.1_json.jinja
      env:
        - name: SERVED_MODEL_NAME # Pass it as env var for the case where model supports Fine-Tuning
          value: {{ .Values.vllm.serveModelName }}
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: {{ $gpus }}
        limits:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: {{ $gpus }}

      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 200

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
  engineConfig:
    {{- if or .Values.commonAnnotations .Values.llama_3_3_70b_instruct.annotations }}
    annotations:
      {{- if .Values.commonAnnotations }}
      {{ toYaml .Values.commonAnnotations | nindent 6 }}
      {{- end }}
      {{- if .Values.llama_3_3_70b_instruct.annotations }}
      {{ toYaml .Values.llama_3_3_70b_instruct.annotations | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.commonLabels .Values.llama_3_3_70b_instruct.labels }}
    labels:
      {{- if .Values.commonLabels }}
      {{ toYaml .Values.commonLabels | nindent 6 }}
      {{- end }}
      {{- if .Values.llama_3_3_70b_instruct.labels }}
      {{ toYaml .Values.llama_3_3_70b_instruct.labels | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.commonTolerations .Values.llama_3_3_70b_instruct.tolerations }}
    tolerations:
      {{- if .Values.commonTolerations }}
      {{ toYaml .Values.commonTolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.llama_3_3_70b_instruct.tolerations }}
      {{ toYaml .Values.llama_3_3_70b_instruct.tolerations | nindent 6 }}
      {{- end }}
    {{- end }}
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      {{- if or (eq .Values.oci.realm "oc5") (eq .Values.oci.realm "oc6") }}
      - name: etc-pki
        hostPath:
          path: /etc/pki
          type: Directory
      {{- end }}
    {{ with .Values.llama_3_3_70b_instruct }}
    affinity: {{ .affinity | toYaml | nindent 6 }}
    {{ end }}
    schedulerName: {{ .Values.commonSchedulerName }}
    runner:
      name: ome-container
      image: {{ .Values.llama_3_3_70b_instruct.image.vllm.repository | default .Values.vllm.commonImage.repository }}:{{ .Values.llama_3_3_70b_instruct.image.vllm.tag | default .Values.vllm.latestImage.tag }}
      ports:
        - containerPort: {{ .Values.vllm.port }}
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          vllm serve "$MODEL_PATH" \
          --port={{ .Values.vllm.port }} \
          --max-log-len=0 \
          --served-model-name="$SERVED_MODEL_NAME" \
          --tensor-parallel-size={{ $gpus }} \
          --max-model-len=131072 \
          --gpu-memory-utilization=0.9 \
          --enable-chunked-prefill \
          --enable-auto-tool-choice \
          --tool-call-parser=llama3_json \
          --chat-template=./examples/tool_chat_template_llama3.1_json.jinja
      env:
        - name: SERVED_MODEL_NAME # Pass it as env var for the case where model supports Fine-Tuning
          value: {{ .Values.vllm.serveModelName }}
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: {{ $gpus }}
        limits:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: {{ $gpus }}
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 200
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60
      startupProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
