// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeInferenceGraphs implements InferenceGraphInterface
type fakeInferenceGraphs struct {
	*gentype.FakeClientWithList[*v1beta1.InferenceGraph, *v1beta1.InferenceGraphList]
	Fake *FakeOmeV1beta1
}

func newFakeInferenceGraphs(fake *FakeOmeV1beta1, namespace string) omev1beta1.InferenceGraphInterface {
	return &fakeInferenceGraphs{
		gentype.NewFakeClientWithList[*v1beta1.InferenceGraph, *v1beta1.InferenceGraphList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("inferencegraphs"),
			v1beta1.SchemeGroupVersion.WithKind("InferenceGraph"),
			func() *v1beta1.InferenceGraph { return &v1beta1.InferenceGraph{} },
			func() *v1beta1.InferenceGraphList { return &v1beta1.InferenceGraphList{} },
			func(dst, src *v1beta1.InferenceGraphList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.InferenceGraphList) []*v1beta1.InferenceGraph {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.InferenceGraphList, items []*v1beta1.InferenceGraph) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
