// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
)

// fakeInferenceReplicas implements InferenceReplicaInterface
type fakeInferenceReplicas struct {
	*gentype.FakeClientWithList[*v1beta1.InferenceReplica, *v1beta1.InferenceReplicaList]
	Fake *FakeOmeV1beta1
}

func newFakeInferenceReplicas(fake *FakeOmeV1beta1, namespace string) omev1beta1.InferenceReplicaInterface {
	return &fakeInferenceReplicas{
		gentype.NewFakeClientWithList[*v1beta1.InferenceReplica, *v1beta1.InferenceReplicaList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("inferencereplicas"),
			v1beta1.SchemeGroupVersion.WithKind("InferenceReplica"),
			func() *v1beta1.InferenceReplica { return &v1beta1.InferenceReplica{} },
			func() *v1beta1.InferenceReplicaList { return &v1beta1.InferenceReplicaList{} },
			func(dst, src *v1beta1.InferenceReplicaList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.InferenceReplicaList) []*v1beta1.InferenceReplica {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.InferenceReplicaList, items []*v1beta1.InferenceReplica) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
