// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
)

// fakeWorkloadClusters implements WorkloadClusterInterface
type fakeWorkloadClusters struct {
	*gentype.FakeClientWithList[*v1beta1.WorkloadCluster, *v1beta1.WorkloadClusterList]
	Fake *FakeOmeV1beta1
}

func newFakeWorkloadClusters(fake *FakeOmeV1beta1) omev1beta1.WorkloadClusterInterface {
	return &fakeWorkloadClusters{
		gentype.NewFakeClientWithList[*v1beta1.WorkloadCluster, *v1beta1.WorkloadClusterList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("workloadclusters"),
			v1beta1.SchemeGroupVersion.WithKind("WorkloadCluster"),
			func() *v1beta1.WorkloadCluster { return &v1beta1.WorkloadCluster{} },
			func() *v1beta1.WorkloadClusterList { return &v1beta1.WorkloadClusterList{} },
			func(dst, src *v1beta1.WorkloadClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.WorkloadClusterList) []*v1beta1.WorkloadCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.WorkloadClusterList, items []*v1beta1.WorkloadCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
