// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDedicatedAIClusters implements DedicatedAIClusterInterface
type FakeDedicatedAIClusters struct {
	Fake *FakeOmeV1beta1
}

var dedicatedaiclustersResource = v1beta1.SchemeGroupVersion.WithResource("dedicatedaiclusters")

var dedicatedaiclustersKind = v1beta1.SchemeGroupVersion.WithKind("DedicatedAICluster")

// Get takes name of the dedicatedAICluster, and returns the corresponding dedicatedAICluster object, and an error if there is any.
func (c *FakeDedicatedAIClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.DedicatedAICluster, err error) {
	emptyResult := &v1beta1.DedicatedAICluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(dedicatedaiclustersResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DedicatedAICluster), err
}

// List takes label and field selectors, and returns the list of DedicatedAIClusters that match those selectors.
func (c *FakeDedicatedAIClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.DedicatedAIClusterList, err error) {
	emptyResult := &v1beta1.DedicatedAIClusterList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(dedicatedaiclustersResource, dedicatedaiclustersKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.DedicatedAIClusterList{ListMeta: obj.(*v1beta1.DedicatedAIClusterList).ListMeta}
	for _, item := range obj.(*v1beta1.DedicatedAIClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dedicatedAIClusters.
func (c *FakeDedicatedAIClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(dedicatedaiclustersResource, opts))
}

// Create takes the representation of a dedicatedAICluster and creates it.  Returns the server's representation of the dedicatedAICluster, and an error, if there is any.
func (c *FakeDedicatedAIClusters) Create(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.CreateOptions) (result *v1beta1.DedicatedAICluster, err error) {
	emptyResult := &v1beta1.DedicatedAICluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(dedicatedaiclustersResource, dedicatedAICluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DedicatedAICluster), err
}

// Update takes the representation of a dedicatedAICluster and updates it. Returns the server's representation of the dedicatedAICluster, and an error, if there is any.
func (c *FakeDedicatedAIClusters) Update(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.UpdateOptions) (result *v1beta1.DedicatedAICluster, err error) {
	emptyResult := &v1beta1.DedicatedAICluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(dedicatedaiclustersResource, dedicatedAICluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DedicatedAICluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDedicatedAIClusters) UpdateStatus(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.UpdateOptions) (result *v1beta1.DedicatedAICluster, err error) {
	emptyResult := &v1beta1.DedicatedAICluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(dedicatedaiclustersResource, "status", dedicatedAICluster, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DedicatedAICluster), err
}

// Delete takes name of the dedicatedAICluster and deletes it. Returns an error if one occurs.
func (c *FakeDedicatedAIClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(dedicatedaiclustersResource, name, opts), &v1beta1.DedicatedAICluster{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDedicatedAIClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(dedicatedaiclustersResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.DedicatedAIClusterList{})
	return err
}

// Patch applies the patch and returns the patched dedicatedAICluster.
func (c *FakeDedicatedAIClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DedicatedAICluster, err error) {
	emptyResult := &v1beta1.DedicatedAICluster{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(dedicatedaiclustersResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.DedicatedAICluster), err
}
