// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTrainingRuntimes implements TrainingRuntimeInterface
type fakeTrainingRuntimes struct {
	*gentype.FakeClientWithList[*v1beta1.TrainingRuntime, *v1beta1.TrainingRuntimeList]
	Fake *FakeOmeV1beta1
}

func newFakeTrainingRuntimes(fake *FakeOmeV1beta1, namespace string) omev1beta1.TrainingRuntimeInterface {
	return &fakeTrainingRuntimes{
		gentype.NewFakeClientWithList[*v1beta1.TrainingRuntime, *v1beta1.TrainingRuntimeList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("trainingruntimes"),
			v1beta1.SchemeGroupVersion.WithKind("TrainingRuntime"),
			func() *v1beta1.TrainingRuntime { return &v1beta1.TrainingRuntime{} },
			func() *v1beta1.TrainingRuntimeList { return &v1beta1.TrainingRuntimeList{} },
			func(dst, src *v1beta1.TrainingRuntimeList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.TrainingRuntimeList) []*v1beta1.TrainingRuntime {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.TrainingRuntimeList, items []*v1beta1.TrainingRuntime) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
