// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOciRedisClusters implements OciRedisClusterInterface
type FakeOciRedisClusters struct {
	Fake *FakeOmeV1beta1
	ns   string
}

var ociredisclustersResource = v1beta1.SchemeGroupVersion.WithResource("ociredisclusters")

var ociredisclustersKind = v1beta1.SchemeGroupVersion.WithKind("OciRedisCluster")

// Get takes name of the ociRedisCluster, and returns the corresponding ociRedisCluster object, and an error if there is any.
func (c *FakeOciRedisClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.OciRedisCluster, err error) {
	emptyResult := &v1beta1.OciRedisCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(ociredisclustersResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.OciRedisCluster), err
}

// List takes label and field selectors, and returns the list of OciRedisClusters that match those selectors.
func (c *FakeOciRedisClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.OciRedisClusterList, err error) {
	emptyResult := &v1beta1.OciRedisClusterList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(ociredisclustersResource, ociredisclustersKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.OciRedisClusterList{ListMeta: obj.(*v1beta1.OciRedisClusterList).ListMeta}
	for _, item := range obj.(*v1beta1.OciRedisClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ociRedisClusters.
func (c *FakeOciRedisClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(ociredisclustersResource, c.ns, opts))

}

// Create takes the representation of a ociRedisCluster and creates it.  Returns the server's representation of the ociRedisCluster, and an error, if there is any.
func (c *FakeOciRedisClusters) Create(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.CreateOptions) (result *v1beta1.OciRedisCluster, err error) {
	emptyResult := &v1beta1.OciRedisCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(ociredisclustersResource, c.ns, ociRedisCluster, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.OciRedisCluster), err
}

// Update takes the representation of a ociRedisCluster and updates it. Returns the server's representation of the ociRedisCluster, and an error, if there is any.
func (c *FakeOciRedisClusters) Update(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.UpdateOptions) (result *v1beta1.OciRedisCluster, err error) {
	emptyResult := &v1beta1.OciRedisCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(ociredisclustersResource, c.ns, ociRedisCluster, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.OciRedisCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOciRedisClusters) UpdateStatus(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.UpdateOptions) (result *v1beta1.OciRedisCluster, err error) {
	emptyResult := &v1beta1.OciRedisCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(ociredisclustersResource, "status", c.ns, ociRedisCluster, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.OciRedisCluster), err
}

// Delete takes name of the ociRedisCluster and deletes it. Returns an error if one occurs.
func (c *FakeOciRedisClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ociredisclustersResource, c.ns, name, opts), &v1beta1.OciRedisCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOciRedisClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(ociredisclustersResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.OciRedisClusterList{})
	return err
}

// Patch applies the patch and returns the patched ociRedisCluster.
func (c *FakeOciRedisClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.OciRedisCluster, err error) {
	emptyResult := &v1beta1.OciRedisCluster{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(ociredisclustersResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.OciRedisCluster), err
}
