// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/typed/ome/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCapacityReservations implements CapacityReservationInterface
type fakeCapacityReservations struct {
	*gentype.FakeClientWithList[*v1beta1.CapacityReservation, *v1beta1.CapacityReservationList]
	Fake *FakeOmeV1beta1
}

func newFakeCapacityReservations(fake *FakeOmeV1beta1, namespace string) omev1beta1.CapacityReservationInterface {
	return &fakeCapacityReservations{
		gentype.NewFakeClientWithList[*v1beta1.CapacityReservation, *v1beta1.CapacityReservationList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("capacityreservations"),
			v1beta1.SchemeGroupVersion.WithKind("CapacityReservation"),
			func() *v1beta1.CapacityReservation { return &v1beta1.CapacityReservation{} },
			func() *v1beta1.CapacityReservationList { return &v1beta1.CapacityReservationList{} },
			func(dst, src *v1beta1.CapacityReservationList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.CapacityReservationList) []*v1beta1.CapacityReservation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.CapacityReservationList, items []*v1beta1.CapacityReservation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
