// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCapacityReservations implements CapacityReservationInterface
type FakeCapacityReservations struct {
	Fake *FakeOmeV1beta1
	ns   string
}

var capacityreservationsResource = v1beta1.SchemeGroupVersion.WithResource("capacityreservations")

var capacityreservationsKind = v1beta1.SchemeGroupVersion.WithKind("CapacityReservation")

// Get takes name of the capacityReservation, and returns the corresponding capacityReservation object, and an error if there is any.
func (c *FakeCapacityReservations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.CapacityReservation, err error) {
	emptyResult := &v1beta1.CapacityReservation{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(capacityreservationsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.CapacityReservation), err
}

// List takes label and field selectors, and returns the list of CapacityReservations that match those selectors.
func (c *FakeCapacityReservations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.CapacityReservationList, err error) {
	emptyResult := &v1beta1.CapacityReservationList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(capacityreservationsResource, capacityreservationsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.CapacityReservationList{ListMeta: obj.(*v1beta1.CapacityReservationList).ListMeta}
	for _, item := range obj.(*v1beta1.CapacityReservationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested capacityReservations.
func (c *FakeCapacityReservations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(capacityreservationsResource, c.ns, opts))

}

// Create takes the representation of a capacityReservation and creates it.  Returns the server's representation of the capacityReservation, and an error, if there is any.
func (c *FakeCapacityReservations) Create(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.CreateOptions) (result *v1beta1.CapacityReservation, err error) {
	emptyResult := &v1beta1.CapacityReservation{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(capacityreservationsResource, c.ns, capacityReservation, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.CapacityReservation), err
}

// Update takes the representation of a capacityReservation and updates it. Returns the server's representation of the capacityReservation, and an error, if there is any.
func (c *FakeCapacityReservations) Update(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.UpdateOptions) (result *v1beta1.CapacityReservation, err error) {
	emptyResult := &v1beta1.CapacityReservation{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(capacityreservationsResource, c.ns, capacityReservation, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.CapacityReservation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCapacityReservations) UpdateStatus(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.UpdateOptions) (result *v1beta1.CapacityReservation, err error) {
	emptyResult := &v1beta1.CapacityReservation{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(capacityreservationsResource, "status", c.ns, capacityReservation, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.CapacityReservation), err
}

// Delete takes name of the capacityReservation and deletes it. Returns an error if one occurs.
func (c *FakeCapacityReservations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(capacityreservationsResource, c.ns, name, opts), &v1beta1.CapacityReservation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCapacityReservations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(capacityreservationsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.CapacityReservationList{})
	return err
}

// Patch applies the patch and returns the patched capacityReservation.
func (c *FakeCapacityReservations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CapacityReservation, err error) {
	emptyResult := &v1beta1.CapacityReservation{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(capacityreservationsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.CapacityReservation), err
}
