apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vllm-one-card-embeding.yaml
  - vllm-large-text-generation.yaml
  - vllm-medium-text-generation.yaml
  - vllm-pp-rdma.yaml
  - vllm-pp.yaml
  - vllm-small-text-generation.yaml
  - vllm-vision.yaml
  - sglang-large-text-generation.yaml
  - sglang-medium-text-generation.yaml
  - sglang-small-text-generation.yaml
  - sglang-xsmall-text-generation.yaml