apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent/mistral-7b-instruct-v0-2-ft-action-v0-0-chat.yaml
  - agent/mistral-7b-instruct-v0-2-ft-action-v0-1-chat.yaml
  - agent/mistral-7b-instruct-v0-2-ft-thought-v0-0-chat.yaml
  - agent/mistral-7b-instruct-v0-2-ft-thought-v0-1-chat.yaml
  - agent/nl2rqs-7b-v3.yaml
  - agent/nl2rqs-7b-v4.yaml
  - agent/nl2sql-m1-base-7b.yaml
  - cohere/6b-v14-2-gen.yaml
  - cohere/6b-v15-6-gen.yaml
  - cohere/52b-v14-2-gen.yaml
  - cohere/52b-v15-6-gen.yaml
  - cohere/cohere-rerank.yaml
  - cohere/command2-35b-v19-0-0-float32-v1-2-16k-ft.yaml
  - cohere/command2-35b-v20-1-0-float32-v1-7-16k-ft.yaml
  - cohere/command-1-6b-v14-2-0.yaml
  - cohere/command-1-6b-v15-6-0.yaml
  - cohere/command-1-52b-v14-2-0.yaml
  - cohere/command-1-52b-v15-6-0.yaml
  - cohere/command-1-52b-v16-0-0.yaml
  - cohere/command-1-v15-6-0-trt.yaml
  - cohere/command-1-v15-6-1-trt.yaml
  - cohere/command-1-v16-0-0-trt.yaml
  - cohere/command-a-032025.yaml
  - cohere/command-a-032025-drcc.yaml
  - cohere/command-r-082024-v1-6-tp4-128k.yaml
  - cohere/command-r-082024-v1-7-tp1-16k.yaml
  - cohere/command-r-082024-v1-7-tp1-128k.yaml
  - cohere/command-r-bs128-16k.yaml
  - cohere/command-r-plus-082024-v1-6-128k.yaml
  - cohere/command-r-plus-v1-2.yaml
  - cohere/command-r-v1-2-16k.yaml
  - cohere/command-r-v1-3-16k.yaml
  - cohere/command-r-v1-6-16k.yaml
  - cohere/command-r-plus-v1-6-128k.yaml
  - cohere/embed-english-light-v2-0.yaml
  - cohere/embed-english-light-v3-0.yaml
  - cohere/embed-english-v3-0.yaml
  - cohere/embed-multilingual-light-v3-0.yaml
  - cohere/embed-multilingual-v3-0.yaml
  - cohere/embed-english-image-v3-0.yaml
  - cohere/embed-english-light-image-v3-0.yaml
  - cohere/embed-multilingual-image-v3-0.yaml
  - cohere/embed-multilingual-light-image-v3-0.yaml
  - cohere/embed-v4.yaml
  - cohere/rerank-english-v3-0.yaml
  - cohere/rerank-multilingual-v3-0.yaml
  - cohere/rerank-v3-5.yaml
  - meta/Llama-3.1-70B-Instruct.yaml
  - meta/Llama-3.1-405B-Instruct-FP8.yaml
  - meta/Llama-3.2-1B-Instruct.yaml
  - meta/Llama-3.2-3B-Instruct.yaml
  - meta/Llama-3.2-11B-Vision-Instruct.yaml
  - meta/Llama-3.2-90B-Vision-Instruct-FP8-Dynamic.yaml
  - meta/Llama-3.3-70B-instruct.yaml
  - meta/Llama-3.3-70B-instruct-FP8-Dynamic.yaml
  - meta/llama-4-maverick-17b-128e-instruct-fp8.yaml
  - meta/llama-4-scout-17b-16e-instruct.yaml
  - intfloat/e5-mistral-7b-instruct.yaml
  - microsoft/Phi-3-vision-128k-instruct.yaml
  - nvidia/Llama-3.1-Nemotron-Nano-8B-v1.yaml
  - nvidia/Llama-3_1-Nemotron-Ultra-253B-v1.yaml
  - nvidia/Llama-3_3-Nemotron-Super-49B-v1.yaml
  - agent/phi-3-vision-128k-instruct-ft-v1.yaml
  - deepseek-ai/DeepSeek-V3.yaml
  - deepseek-ai/DeepSeek-R1.yaml
  - openai/gpt-4o.yaml
  - openai/gpt-4o-2024-08-06.yaml
  - openai/gpt-4o-2024-11-20.yaml
  - openai/gpt-4o-mini.yaml
  - openai/gpt-4o-mini-2024-07-18.yaml
  - openai/o1.yaml
  - openai/o1-2024-12-17.yaml
  - openai/o3-mini.yaml
  - openai/o3-mini-2025-01-31.yaml