apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: mistral-7b-v0-2-finetuned-model-action-v0-0
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: "vllm-xsmall-text-generation"
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "True"
    models.ome.io/internal: "True"
    models.ome.io/lifecycle-phase: "ACTIVE"
spec:
  compartmentID: ocid1.compartment.oc1..aaaaaaaazq
  disabled: false
  displayName: olm.mistral-7b-instruct-v0.2-ft-action
  storage:
    path: oci://n/idlsnvn0f2is/b/model-store/o/olm/action-mistral-7b-v0.2-finetuned-model-v0.0
    storageUri: /raid/models/olm/action-mistral-7b-v0.2-finetuned-model-v0.0
  vendor: olm
  version: "0.0"
  modelFormat:
    name: safetensors
    version: "1"
  modelType: transformer
  modelArchitecture: MistralForCausalLM
  modelParameterSize: 7B
  modelCapabilities:
    - "CHAT"
  maxTokens: 32768
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: SMALL_GENERIC_V2
          quotaUnit: 1
          default: true
