---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: servingruntime-preset.ome.io
  annotations:
    cert-manager.io/inject-ca-from: ome/serving-cert
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: ome-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-ome-io-v1beta1-servingruntime-preset
    failurePolicy: Fail
    name: servingruntime.ome-webhook-server.preset
    sideEffects: None
    admissionReviewVersions: ["v1"]
    matchConditions:
      - name: skip-deletion
        expression: "!has(object.metadata.deletionTimestamp)"
    rules:
      - apiGroups:
          - ome.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servingruntimes
  - clientConfig:
      caBundle: Cg==
      service:
        name: ome-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-ome-io-v1beta1-clusterservingruntime-preset
    failurePolicy: Fail
    name: clusterservingruntime.ome-webhook-server.preset
    sideEffects: None
    admissionReviewVersions: ["v1"]
    matchConditions:
      - name: skip-deletion
        expression: "!has(object.metadata.deletionTimestamp)"
    rules:
      - apiGroups:
          - ome.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterservingruntimes
