apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-download-agent.fullname" . }}
  labels:
    {{- include "generic-download-agent.labels" . | nindent 4 }}
  {{- if .Values.enableHooks }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
  {{- end }}
data:
  MODEL_NAME: "{{ .Values.containerEnv.modelName }}"
  AUTH_TYPE: "{{ .Values.containerEnv.authType }}"
  ENABLE_SIZE_LIMIT_CHECK: "{{ .Values.containerEnv.enableSizeLimitCheck }}"
  NUM_OF_THREADS_FOR_REPLICATION: "{{ .Values.containerEnv.numOfThreadsForReplication }}"
  SOURCE_OBJECT_BUCKET_NAME: "{{ .Values.containerEnv.sourceObjectBucketName }}"
  SOURCE_OBJECT_PREFIX: "{{ .Values.containerEnv.sourceObjectPrefix }}"
  SOURCE_OBJECT_COMPARTMENT_ID: "{{ .Values.containerEnv.sourceObjectCompartmentId }}"
  SOURCE_REGION_OVERRIDE: "{{ .Values.containerEnv.sourceRegionOverride }}"
  SOURCE_ENABLE_OBO_TOKEN: "{{ .Values.containerEnv.sourceEnableOboToken }}"
  SOURCE_OBO_TOKEN: "{{ .Values.containerEnv.sourceOboToken }}"
  TARGET_OBJECT_BUCKET_NAME: "{{ .Values.containerEnv.targetObjectBucketName }}"
  TARGET_OBJECT_PREFIX: "{{ .Values.containerEnv.targetObjectPrefix }}"
  TARGET_OBJECT_COMPARTMENT_ID: "{{ .Values.containerEnv.targetObjectCompartmentId }}"
  REGION: "{{ .Values.containerEnv.region }}"


