ome:
  version: &defaultVersion v0.0.1
  metricsaggregator:
    enableMetricAggregation: "false"
    enablePrometheusScraping: "false"
  ociETC:
    region: us-chicago-1
    serviceTenancyId: ocid1.tenancy.oc1..aaaaaaaa6kumpbo73nsadhi7t4ssehtgn6wtnnkertn6sd74i4gzvia6misa
    serviceCompartmentId: ocid1.compartment.oc1..aaaaaaaal2wsx6r54lwfqa7frqad33ujlgo4azwd2uv6ftyqmvbqm6k5dxaa
    stage: dev
    realm: oc1
    applicationStage: prod
    publicDomainName: oraclecloud.com
    internalDomainName: oracleiaas.com
    airportCode: ORD
    adNumberName: ad2
    namespace: ax0pqskufyud
  controller:
    replicaCount: 3
    deploymentMode: "RawDeployment"
    rbacProxyImage: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
    ingressGateway:
      domain: svc.cluster.local
      domainTemplate: "{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}"
      urlScheme: http
      disableIstioVirtualHost: false
      localGateway:
        gateway: knative-serving/knative-local-gateway
        gatewayService: knative-local-gateway.istio-system.svc.cluster.local
      ingressGateway:
        gateway: knative-serving/knative-ingress-gateway
        gatewayService: istio-ingressgateway.istio-system.svc.cluster.local
        className: istio
    nodeSelector: {}
    tolerations: []
    topologySpreadConstraints: []
    affinity: {}
    image: ord.ocir.io/idqj093njucb/ome/manager
    tag: *defaultVersion
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
  servingruntime:
    vllmMedium:
      image: fra.ocir.io/idqj093njucb/official-vllm-openai
      tag: e3c664b
  modelController:
    serviceAccount: ome-model-controller
    replicaCount: 3
    nodeSelector: {}
    tolerations: []
    topologySpreadConstraints: []
    affinity: {}
    image: ord.ocir.io/idqj093njucb/model-controller
    tag: *defaultVersion

modelAgent:
  # each host has different nvme mount configured, so we need to mount the hostPath to the correct path
  # all mairon cluster nodes have the nvme path as /raid and all service cluster nodes have the nvme path as /mnt/data
  hostPath: /mnt/data/models
  hostPathType: DirectoryOrCreate
  priorityClassName: system-node-critical
  serviceAccountName: ome-model-agent

  image:
    repository: eu-frankfurt-1.ocir.io/idlsnvn0f2is/model-agent
    pullPolicy: Always
    tag: v0.1
  
  # this affinity is not applicable in moirai cluster yet
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: In
            values:
            - "true"

  nodeSelector: {}
  
  moiraiCluster: false
  moiraiClusterAffinity: {}
  moiraiClusterNodeSelector:
    node.kubernetes.io/instance-type: BM.GPU.H100.8
  
  health:
    port: 8080
  
  resources:
    limits:
      cpu: '10'
      memory: 100Gi
    requests:
      cpu: '10'
      memory: 100Gi
