apiVersion: v1
kind: Namespace
metadata:
  name: isvc-router-test-1
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    ome.io/deploymentMode: RawDeployment
    ome.io/service-type: ClusterIP
    ome.io/entrypoint-component: router
  name: llama-3-2-1b-instruct
  namespace: isvc-router-test-1
spec:
  predictor:
    model:
      runtime: srt-llama-3-2-1b-instruct
      baseModel: llama-3-2-1b-instruct
      protocolVersion: openAI
      resources: {}
    minReplicas: 3
    maxReplicas: 4
    workerSpec: {}
  router:
    minReplicas: 1
    maxReplicas: 2