---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-3-1-70b
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-70b
  namespace: llama-3-1-70b
  annotations:
    ome.io/autoscalerClass: "keda"
spec:
  predictor:
    model:
      baseModel: llama-3-1-70b
      protocolVersion: openAI
    minReplicas: 1
    maxReplicas: 2

  kedaConfig:
    enableKeda: true
    promServerAddress: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
    customPromQuery: ""
    scalingThreshold: "1"
    scalingOperator: "GreaterThanOrEqual"