---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-3-1-70b
---

apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-70b
  namespace: llama-3-1-70b
spec:
  predictor:
    model:
      runtime: vllm-medium-text-generation
      baseModel: llama-3-1-70b
      protocolVersion: openAI
    minReplicas: 1
    maxReplicas: 2