compartmentID: ocid1.compartment.oc1..aaaaaaaazq
osnamespace: mynamespace

llama-3-1-405b-instruct-fp8:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-1-70b-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-1-70b-instruct-2024-12:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-90b-vision:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-90b-vision-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-90b-vision-instruct-fp8-dynamic:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-11b-vision:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-11b-vision-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-1b:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-1b-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-3b:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-2-3b-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

llama-3-70b-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

mixtral-8x7b-instruct-v0-1-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

e5-mistral-7b-instruct:
  enabled: false
  lifecyclePhase: "ACTIVE"

deberta-v3-base-prompt-injection-v2:
  enabled: false

gliner-large-v2-1:
  enabled: false

mistral-7b-instruct-v0-2-ft-action-v0-0-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

mistral-7b-instruct-v0-2-ft-action-v0-1-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

mistral-7b-instruct-v0-2-ft-thought-v0-0-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

mistral-7b-instruct-v0-2-ft-thought-v0-1-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

phi-3-vision-128k-instruct-chat:
  enabled: false
  lifecyclePhase: "ACTIVE"

phi-3-vision-128k-instruct-ft-v1:
  enabled: false
  lifecyclePhase: "ACTIVE"

nl2sql-m1-base-7b:
  enabled: false
  lifecyclePhase: "ACTIVE"

nl2rqs-7b-v3:
  enabled: false
  lifecyclePhase: "ACTIVE"

nl2rqs-7b-v4:
  enabled: false
  lifecyclePhase: "ACTIVE"

cohere-command-r-082024-v1-6-tp4-128k:
  enabled: false 
  lifecyclePhase: "ACTIVE"
