# coding: utf-8

"""
    OME

    Python SDK for OME

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class V1beta1ServiceMetadata(BaseModel):
    """
    ServiceMetadata contains metadata fields for recording the backend model server's configuration and version details. This information helps track experiment context, enabling users to filter and query experiments based on server properties.
    """ # noqa: E501
    engine: StrictStr = Field(description="Engine specifies the backend model server engine. Supported values: \"vLLM\", \"SGLang\", \"TGI\".")
    gpu_count: StrictInt = Field(description="GpuCount indicates the number of GPU cards available on the model server.", alias="gpuCount")
    gpu_type: StrictStr = Field(description="GpuType specifies the type of GPU used by the model server. Supported values: \"H100\", \"A100\", \"MI300\", \"A10\".", alias="gpuType")
    version: StrictStr = Field(description="Version specifies the version of the model server (e.g., \"0.5.3\").")
    __properties: ClassVar[List[str]] = ["engine", "gpuCount", "gpuType", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1beta1ServiceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1beta1ServiceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "engine": obj.get("engine") if obj.get("engine") is not None else '',
            "gpuCount": obj.get("gpuCount") if obj.get("gpuCount") is not None else 0,
            "gpuType": obj.get("gpuType") if obj.get("gpuType") is not None else '',
            "version": obj.get("version") if obj.get("version") is not None else ''
        })
        return _obj


