# coding: utf-8

"""
    OME

    Python SDK for OME

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ome.models.v1beta1_built_in_adapter import V1beta1BuiltInAdapter
from ome.models.v1beta1_model_size_range_spec import V1beta1ModelSizeRangeSpec
from ome.models.v1beta1_supported_model_format import V1beta1SupportedModelFormat
from ome.models.v1beta1_worker_pod_spec import V1beta1WorkerPodSpec
from typing import Optional, Set
from typing_extensions import Self

class V1beta1ServingRuntimeSpec(BaseModel):
    """
    ServingRuntimeSpec defines the desired state of ServingRuntime. This spec is currently provisional and are subject to change as details regarding single-model serving and multi-model serving are hammered out.
    """ # noqa: E501
    affinity: Optional[V1Affinity] = None
    annotations: Optional[Dict[str, StrictStr]] = Field(default=None, description="Annotations that will be add to the pod. More info: http://kubernetes.io/docs/user-guide/annotations")
    built_in_adapter: Optional[V1beta1BuiltInAdapter] = Field(default=None, alias="builtInAdapter")
    compartment_id: Optional[StrictStr] = Field(default=None, description="The compartment ID to use for the serving runtime", alias="compartmentID")
    containers: List[V1Container] = Field(description="List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. Cannot be updated.")
    disabled: Optional[StrictBool] = Field(default=None, description="Set to true to disable use of this runtime")
    dns_policy: Optional[StrictStr] = Field(default=None, description="Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'.", alias="dnsPolicy")
    host_ipc: Optional[StrictBool] = Field(default=None, description="Use the host's ipc namespace. Optional: Default to false.", alias="hostIPC")
    host_network: Optional[StrictBool] = Field(default=None, description="Host networking requested for this pod. Use the host's network namespace. If this option is set, the ports that will be used must be specified. Default to false.", alias="hostNetwork")
    http_data_endpoint: Optional[StrictStr] = Field(default=None, description="HTTP endpoint for inferencing", alias="httpDataEndpoint")
    image_pull_secrets: Optional[List[V1LocalObjectReference]] = Field(default=None, description="ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod", alias="imagePullSecrets")
    labels: Optional[Dict[str, StrictStr]] = Field(default=None, description="Labels that will be add to the pod. More info: http://kubernetes.io/docs/user-guide/labels")
    model_size_range: Optional[V1beta1ModelSizeRangeSpec] = Field(default=None, alias="modelSizeRange")
    node_selector: Optional[Dict[str, StrictStr]] = Field(default=None, description="NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/", alias="nodeSelector")
    pipeline_parallelism: Optional[StrictBool] = Field(default=None, description="Enable pipeline parallelism for the runtime When pipeline parallelism is enabled, the runtime informs the model server to use pipeline parallelism for model inference with multiple compute nodes via Ray Cluster and vLLM only. The number of compute nodes is determined by the number of replicas in the Inference Service. The worker node will be minimum replica minus one, which is reserved for head node. This field is deprecated and will be removed in a future release. Please use the annotation \"ome.io/deploymentMode: MultiNodeRayVLLM\" instead.", alias="pipelineParallelism")
    protocol_versions: Optional[List[StrictStr]] = Field(default=None, description="Supported protocol versions (i.e. openAI or cohere or openInference-v1 or openInference-v2)", alias="protocolVersions")
    replicas: Optional[StrictInt] = Field(default=None, description="Configure the number of replicas in the Deployments generated by this ServingRuntime If specified, this overrides the podsPerRuntime configuration value")
    scheduler_name: Optional[StrictStr] = Field(default=None, description="If specified, the pod will be dispatched by specified scheduler. If not specified, the pod will be dispatched by default scheduler.", alias="schedulerName")
    supported_model_formats: Optional[List[V1beta1SupportedModelFormat]] = Field(default=None, description="Model formats and version supported by this runtime", alias="supportedModelFormats")
    tolerations: Optional[List[V1Toleration]] = Field(default=None, description="If specified, the pod's tolerations.")
    volumes: Optional[List[V1Volume]] = Field(default=None, description="List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes")
    workers: Optional[V1beta1WorkerPodSpec] = None
    __properties: ClassVar[List[str]] = ["affinity", "annotations", "builtInAdapter", "compartmentID", "containers", "disabled", "dnsPolicy", "hostIPC", "hostNetwork", "httpDataEndpoint", "imagePullSecrets", "labels", "modelSizeRange", "nodeSelector", "pipelineParallelism", "protocolVersions", "replicas", "schedulerName", "supportedModelFormats", "tolerations", "volumes", "workers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1beta1ServingRuntimeSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of affinity
        if self.affinity:
            _dict['affinity'] = self.affinity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of built_in_adapter
        if self.built_in_adapter:
            _dict['builtInAdapter'] = self.built_in_adapter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in containers (list)
        _items = []
        if self.containers:
            for _item_containers in self.containers:
                if _item_containers:
                    _items.append(_item_containers.to_dict())
            _dict['containers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in image_pull_secrets (list)
        _items = []
        if self.image_pull_secrets:
            for _item_image_pull_secrets in self.image_pull_secrets:
                if _item_image_pull_secrets:
                    _items.append(_item_image_pull_secrets.to_dict())
            _dict['imagePullSecrets'] = _items
        # override the default output from pydantic by calling `to_dict()` of model_size_range
        if self.model_size_range:
            _dict['modelSizeRange'] = self.model_size_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in supported_model_formats (list)
        _items = []
        if self.supported_model_formats:
            for _item_supported_model_formats in self.supported_model_formats:
                if _item_supported_model_formats:
                    _items.append(_item_supported_model_formats.to_dict())
            _dict['supportedModelFormats'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tolerations (list)
        _items = []
        if self.tolerations:
            for _item_tolerations in self.tolerations:
                if _item_tolerations:
                    _items.append(_item_tolerations.to_dict())
            _dict['tolerations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict['volumes'] = _items
        # override the default output from pydantic by calling `to_dict()` of workers
        if self.workers:
            _dict['workers'] = self.workers.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1beta1ServingRuntimeSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "affinity": V1Affinity.from_dict(obj["affinity"]) if obj.get("affinity") is not None else None,
            "annotations": obj.get("annotations"),
            "builtInAdapter": V1beta1BuiltInAdapter.from_dict(obj["builtInAdapter"]) if obj.get("builtInAdapter") is not None else None,
            "compartmentID": obj.get("compartmentID"),
            "containers": [V1Container.from_dict(_item) for _item in obj["containers"]] if obj.get("containers") is not None else None,
            "disabled": obj.get("disabled"),
            "dnsPolicy": obj.get("dnsPolicy"),
            "hostIPC": obj.get("hostIPC"),
            "hostNetwork": obj.get("hostNetwork"),
            "httpDataEndpoint": obj.get("httpDataEndpoint"),
            "imagePullSecrets": [V1LocalObjectReference.from_dict(_item) for _item in obj["imagePullSecrets"]] if obj.get("imagePullSecrets") is not None else None,
            "labels": obj.get("labels"),
            "modelSizeRange": V1beta1ModelSizeRangeSpec.from_dict(obj["modelSizeRange"]) if obj.get("modelSizeRange") is not None else None,
            "nodeSelector": obj.get("nodeSelector"),
            "pipelineParallelism": obj.get("pipelineParallelism"),
            "protocolVersions": obj.get("protocolVersions"),
            "replicas": obj.get("replicas"),
            "schedulerName": obj.get("schedulerName"),
            "supportedModelFormats": [V1beta1SupportedModelFormat.from_dict(_item) for _item in obj["supportedModelFormats"]] if obj.get("supportedModelFormats") is not None else None,
            "tolerations": [V1Toleration.from_dict(_item) for _item in obj["tolerations"]] if obj.get("tolerations") is not None else None,
            "volumes": [V1Volume.from_dict(_item) for _item in obj["volumes"]] if obj.get("volumes") is not None else None,
            "workers": V1beta1WorkerPodSpec.from_dict(obj["workers"]) if obj.get("workers") is not None else None
        })
        return _obj


