# coding: utf-8

"""
OME

Python SDK for OME  # noqa: E501

The version of the OpenAPI document: v0.1
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from ome.configuration import Configuration


class V1beta1AssociationUsage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "name": "str",
        "usage": "list[SigsK8sIoKueueApisKueueV1beta1FlavorUsage]",
    }

    attribute_map = {"name": "name", "usage": "usage"}

    def __init__(self, name="", usage=None, local_vars_configuration=None):  # noqa: E501
        """V1beta1AssociationUsage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._usage = None
        self.discriminator = None

        self.name = name
        self.usage = usage

    @property
    def name(self):
        """Gets the name of this V1beta1AssociationUsage.  # noqa: E501

        Name of the association.  # noqa: E501

        :return: The name of this V1beta1AssociationUsage.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1beta1AssociationUsage.

        Name of the association.  # noqa: E501

        :param name: The name of this V1beta1AssociationUsage.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def usage(self):
        """Gets the usage of this V1beta1AssociationUsage.  # noqa: E501

        Usage of the association.  # noqa: E501

        :return: The usage of this V1beta1AssociationUsage.  # noqa: E501
        :rtype: list[SigsK8sIoKueueApisKueueV1beta1FlavorUsage]
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this V1beta1AssociationUsage.

        Usage of the association.  # noqa: E501

        :param usage: The usage of this V1beta1AssociationUsage.  # noqa: E501
        :type: list[SigsK8sIoKueueApisKueueV1beta1FlavorUsage]
        """
        if self.local_vars_configuration.client_side_validation and usage is None:  # noqa: E501
            raise ValueError("Invalid value for `usage`, must not be `None`")  # noqa: E501

        self._usage = usage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1AssociationUsage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1AssociationUsage):
            return True

        return self.to_dict() != other.to_dict()
