# coding: utf-8

"""
OME

Python SDK for OME  # noqa: E501

The version of the OpenAPI document: v0.1
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from ome.configuration import Configuration


class V1beta1ProjectSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "config": "dict(str, str)",
        "description": "str",
        "name": "str",
        "organization_ref": "V1beta1CrossReference",
    }

    attribute_map = {
        "config": "config",
        "description": "description",
        "name": "name",
        "organization_ref": "organizationRef",
    }

    def __init__(
        self,
        config=None,
        description=None,
        name="",
        organization_ref=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """V1beta1ProjectSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._config = None
        self._description = None
        self._name = None
        self._organization_ref = None
        self.discriminator = None

        if config is not None:
            self.config = config
        if description is not None:
            self.description = description
        self.name = name
        self.organization_ref = organization_ref

    @property
    def config(self):
        """Gets the config of this V1beta1ProjectSpec.  # noqa: E501

        Config contains vendor-specific configuration  # noqa: E501

        :return: The config of this V1beta1ProjectSpec.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this V1beta1ProjectSpec.

        Config contains vendor-specific configuration  # noqa: E501

        :param config: The config of this V1beta1ProjectSpec.  # noqa: E501
        :type: dict(str, str)
        """

        self._config = config

    @property
    def description(self):
        """Gets the description of this V1beta1ProjectSpec.  # noqa: E501

        Description is the project description  # noqa: E501

        :return: The description of this V1beta1ProjectSpec.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1beta1ProjectSpec.

        Description is the project description  # noqa: E501

        :param description: The description of this V1beta1ProjectSpec.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this V1beta1ProjectSpec.  # noqa: E501

        Name is the project name  # noqa: E501

        :return: The name of this V1beta1ProjectSpec.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1beta1ProjectSpec.

        Name is the project name  # noqa: E501

        :param name: The name of this V1beta1ProjectSpec.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def organization_ref(self):
        """Gets the organization_ref of this V1beta1ProjectSpec.  # noqa: E501


        :return: The organization_ref of this V1beta1ProjectSpec.  # noqa: E501
        :rtype: V1beta1CrossReference
        """
        return self._organization_ref

    @organization_ref.setter
    def organization_ref(self, organization_ref):
        """Sets the organization_ref of this V1beta1ProjectSpec.


        :param organization_ref: The organization_ref of this V1beta1ProjectSpec.  # noqa: E501
        :type: V1beta1CrossReference
        """
        if (
            self.local_vars_configuration.client_side_validation
            and organization_ref is None
        ):  # noqa: E501
            raise ValueError("Invalid value for `organization_ref`, must not be `None`")  # noqa: E501

        self._organization_ref = organization_ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1ProjectSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1ProjectSpec):
            return True

        return self.to_dict() != other.to_dict()
