# coding: utf-8

"""
OME

Python SDK for OME  # noqa: E501

The version of the OpenAPI document: v0.1
Generated by: https://openapi-generator.tech
"""

import pprint
import re  # noqa: F401

import six

from ome.configuration import Configuration


class V1beta1FineTunedWeightSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "base_model_ref": "V1beta1ObjectReference",
        "compartment_id": "str",
        "configuration": "K8sIoApimachineryPkgRuntimeRawExtension",
        "disabled": "bool",
        "display_name": "str",
        "hyper_parameters": "K8sIoApimachineryPkgRuntimeRawExtension",
        "model_type": "str",
        "storage": "V1beta1StorageSpec",
        "training_job_ref": "V1beta1ObjectReference",
        "vendor": "str",
        "version": "str",
    }

    attribute_map = {
        "base_model_ref": "baseModelRef",
        "compartment_id": "compartmentID",
        "configuration": "configuration",
        "disabled": "disabled",
        "display_name": "displayName",
        "hyper_parameters": "hyperParameters",
        "model_type": "modelType",
        "storage": "storage",
        "training_job_ref": "trainingJobRef",
        "vendor": "vendor",
        "version": "version",
    }

    def __init__(
        self,
        base_model_ref=None,
        compartment_id=None,
        configuration=None,
        disabled=None,
        display_name=None,
        hyper_parameters=None,
        model_type=None,
        storage=None,
        training_job_ref=None,
        vendor=None,
        version=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """V1beta1FineTunedWeightSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._base_model_ref = None
        self._compartment_id = None
        self._configuration = None
        self._disabled = None
        self._display_name = None
        self._hyper_parameters = None
        self._model_type = None
        self._storage = None
        self._training_job_ref = None
        self._vendor = None
        self._version = None
        self.discriminator = None

        self.base_model_ref = base_model_ref
        if compartment_id is not None:
            self.compartment_id = compartment_id
        if configuration is not None:
            self.configuration = configuration
        if disabled is not None:
            self.disabled = disabled
        if display_name is not None:
            self.display_name = display_name
        self.hyper_parameters = hyper_parameters
        self.model_type = model_type
        self.storage = storage
        if training_job_ref is not None:
            self.training_job_ref = training_job_ref
        if vendor is not None:
            self.vendor = vendor
        if version is not None:
            self.version = version

    @property
    def base_model_ref(self):
        """Gets the base_model_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The base_model_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: V1beta1ObjectReference
        """
        return self._base_model_ref

    @base_model_ref.setter
    def base_model_ref(self, base_model_ref):
        """Sets the base_model_ref of this V1beta1FineTunedWeightSpec.


        :param base_model_ref: The base_model_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: V1beta1ObjectReference
        """
        if (
            self.local_vars_configuration.client_side_validation
            and base_model_ref is None
        ):  # noqa: E501
            raise ValueError("Invalid value for `base_model_ref`, must not be `None`")  # noqa: E501

        self._base_model_ref = base_model_ref

    @property
    def compartment_id(self):
        """Gets the compartment_id of this V1beta1FineTunedWeightSpec.  # noqa: E501

        CompartmentID is the compartment ID of the model  # noqa: E501

        :return: The compartment_id of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: str
        """
        return self._compartment_id

    @compartment_id.setter
    def compartment_id(self, compartment_id):
        """Sets the compartment_id of this V1beta1FineTunedWeightSpec.

        CompartmentID is the compartment ID of the model  # noqa: E501

        :param compartment_id: The compartment_id of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: str
        """

        self._compartment_id = compartment_id

    @property
    def configuration(self):
        """Gets the configuration of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The configuration of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: K8sIoApimachineryPkgRuntimeRawExtension
        """
        return self._configuration

    @configuration.setter
    def configuration(self, configuration):
        """Sets the configuration of this V1beta1FineTunedWeightSpec.


        :param configuration: The configuration of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: K8sIoApimachineryPkgRuntimeRawExtension
        """

        self._configuration = configuration

    @property
    def disabled(self):
        """Gets the disabled of this V1beta1FineTunedWeightSpec.  # noqa: E501

        Whether the model is enabled or not  # noqa: E501

        :return: The disabled of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this V1beta1FineTunedWeightSpec.

        Whether the model is enabled or not  # noqa: E501

        :param disabled: The disabled of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def display_name(self):
        """Gets the display_name of this V1beta1FineTunedWeightSpec.  # noqa: E501

        DisplayName is the user-friendly name of the model  # noqa: E501

        :return: The display_name of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this V1beta1FineTunedWeightSpec.

        DisplayName is the user-friendly name of the model  # noqa: E501

        :param display_name: The display_name of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def hyper_parameters(self):
        """Gets the hyper_parameters of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The hyper_parameters of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: K8sIoApimachineryPkgRuntimeRawExtension
        """
        return self._hyper_parameters

    @hyper_parameters.setter
    def hyper_parameters(self, hyper_parameters):
        """Sets the hyper_parameters of this V1beta1FineTunedWeightSpec.


        :param hyper_parameters: The hyper_parameters of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: K8sIoApimachineryPkgRuntimeRawExtension
        """
        if (
            self.local_vars_configuration.client_side_validation
            and hyper_parameters is None
        ):  # noqa: E501
            raise ValueError("Invalid value for `hyper_parameters`, must not be `None`")  # noqa: E501

        self._hyper_parameters = hyper_parameters

    @property
    def model_type(self):
        """Gets the model_type of this V1beta1FineTunedWeightSpec.  # noqa: E501

        ModelType of the fine-tuned weight, e.g., \"Distillation\", \"Adapter\", \"Tfew\"  # noqa: E501

        :return: The model_type of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: str
        """
        return self._model_type

    @model_type.setter
    def model_type(self, model_type):
        """Sets the model_type of this V1beta1FineTunedWeightSpec.

        ModelType of the fine-tuned weight, e.g., \"Distillation\", \"Adapter\", \"Tfew\"  # noqa: E501

        :param model_type: The model_type of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and model_type is None:  # noqa: E501
            raise ValueError("Invalid value for `model_type`, must not be `None`")  # noqa: E501

        self._model_type = model_type

    @property
    def storage(self):
        """Gets the storage of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The storage of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: V1beta1StorageSpec
        """
        return self._storage

    @storage.setter
    def storage(self, storage):
        """Sets the storage of this V1beta1FineTunedWeightSpec.


        :param storage: The storage of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: V1beta1StorageSpec
        """
        if self.local_vars_configuration.client_side_validation and storage is None:  # noqa: E501
            raise ValueError("Invalid value for `storage`, must not be `None`")  # noqa: E501

        self._storage = storage

    @property
    def training_job_ref(self):
        """Gets the training_job_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The training_job_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: V1beta1ObjectReference
        """
        return self._training_job_ref

    @training_job_ref.setter
    def training_job_ref(self, training_job_ref):
        """Sets the training_job_ref of this V1beta1FineTunedWeightSpec.


        :param training_job_ref: The training_job_ref of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: V1beta1ObjectReference
        """

        self._training_job_ref = training_job_ref

    @property
    def vendor(self):
        """Gets the vendor of this V1beta1FineTunedWeightSpec.  # noqa: E501

        Vendor of the model, e.g., \"NVIDIA\", \"Meta\", \"HuggingFace\"  # noqa: E501

        :return: The vendor of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor):
        """Sets the vendor of this V1beta1FineTunedWeightSpec.

        Vendor of the model, e.g., \"NVIDIA\", \"Meta\", \"HuggingFace\"  # noqa: E501

        :param vendor: The vendor of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: str
        """

        self._vendor = vendor

    @property
    def version(self):
        """Gets the version of this V1beta1FineTunedWeightSpec.  # noqa: E501


        :return: The version of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1beta1FineTunedWeightSpec.


        :param version: The version of this V1beta1FineTunedWeightSpec.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1beta1FineTunedWeightSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1beta1FineTunedWeightSpec):
            return True

        return self.to_dict() != other.to_dict()
