# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class V1beta1PodOverride(BaseModel):
    """
    V1beta1PodOverride
    """  # noqa: E501

    affinity: Optional[V1Affinity] = None
    env: Optional[List[V1EnvVar]] = Field(
        default=None,
        description="List of environment variables to set in the container.",
    )
    env_from: Optional[List[V1EnvFromSource]] = Field(
        default=None,
        description="List of sources to populate environment variables in the container.",
        alias="envFrom",
    )
    image: Optional[StrictStr] = Field(
        default=None,
        description="Image specifies the container image to use for the benchmark job.",
    )
    node_selector: Optional[Dict[str, StrictStr]] = Field(
        default=None,
        description="NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/",
        alias="nodeSelector",
    )
    resources: Optional[V1ResourceRequirements] = None
    tolerations: Optional[List[V1Toleration]] = Field(
        default=None, description="If specified, the pod's tolerations."
    )
    volume_mounts: Optional[List[V1VolumeMount]] = Field(
        default=None,
        description="Pod volumes to mount into the container's filesystem.",
        alias="volumeMounts",
    )
    volumes: Optional[List[V1Volume]] = Field(
        default=None,
        description="List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes",
    )
    __properties: ClassVar[List[str]] = [
        "affinity",
        "env",
        "envFrom",
        "image",
        "nodeSelector",
        "resources",
        "tolerations",
        "volumeMounts",
        "volumes",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1beta1PodOverride from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of affinity
        if self.affinity:
            _dict["affinity"] = self.affinity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict["env"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in env_from (list)
        _items = []
        if self.env_from:
            for _item_env_from in self.env_from:
                if _item_env_from:
                    _items.append(_item_env_from.to_dict())
            _dict["envFrom"] = _items
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict["resources"] = self.resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tolerations (list)
        _items = []
        if self.tolerations:
            for _item_tolerations in self.tolerations:
                if _item_tolerations:
                    _items.append(_item_tolerations.to_dict())
            _dict["tolerations"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volume_mounts (list)
        _items = []
        if self.volume_mounts:
            for _item_volume_mounts in self.volume_mounts:
                if _item_volume_mounts:
                    _items.append(_item_volume_mounts.to_dict())
            _dict["volumeMounts"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volumes (list)
        _items = []
        if self.volumes:
            for _item_volumes in self.volumes:
                if _item_volumes:
                    _items.append(_item_volumes.to_dict())
            _dict["volumes"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1beta1PodOverride from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "affinity": V1Affinity.from_dict(obj["affinity"])
                if obj.get("affinity") is not None
                else None,
                "env": [V1EnvVar.from_dict(_item) for _item in obj["env"]]
                if obj.get("env") is not None
                else None,
                "envFrom": [
                    V1EnvFromSource.from_dict(_item) for _item in obj["envFrom"]
                ]
                if obj.get("envFrom") is not None
                else None,
                "image": obj.get("image"),
                "nodeSelector": obj.get("nodeSelector"),
                "resources": V1ResourceRequirements.from_dict(obj["resources"])
                if obj.get("resources") is not None
                else None,
                "tolerations": [
                    V1Toleration.from_dict(_item) for _item in obj["tolerations"]
                ]
                if obj.get("tolerations") is not None
                else None,
                "volumeMounts": [
                    V1VolumeMount.from_dict(_item) for _item in obj["volumeMounts"]
                ]
                if obj.get("volumeMounts") is not None
                else None,
                "volumes": [V1Volume.from_dict(_item) for _item in obj["volumes"]]
                if obj.get("volumes") is not None
                else None,
            }
        )
        return _obj
