apiVersion: ome.io/v1beta1
kind: AcceleratorClass
metadata:
  name: nvidia-h200-2
spec:
  vendor: nvidia
  family: hopper
  model: h200
  
  discovery:
    nodeSelector:
      nvidia.com/gpu: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: beta.kubernetes.io/instance-type
                  operator: In
                  values:
                    - BM.GPU.H200.8
                    - BM.GPU.H200-NC.8
  
  capabilities:
    computeCapability: "2.0"
  resources:
    - name: cpu
      quantity: "28"
    - name: memory
      quantity: "500Gi"
    - name: nvidia.com/gpu
      quantity: "2"