// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	omev1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	versioned "github.com/sgl-project/sgl-ome/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sgl-project/sgl-ome/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/sgl-project/sgl-ome/pkg/client/listers/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CapacityReservationInformer provides access to a shared informer and lister for
// CapacityReservations.
type CapacityReservationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.CapacityReservationLister
}

type capacityReservationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCapacityReservationInformer constructs a new informer for CapacityReservation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCapacityReservationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCapacityReservationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCapacityReservationInformer constructs a new informer for CapacityReservation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCapacityReservationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().CapacityReservations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().CapacityReservations(namespace).Watch(context.TODO(), options)
			},
		},
		&omev1beta1.CapacityReservation{},
		resyncPeriod,
		indexers,
	)
}

func (f *capacityReservationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCapacityReservationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *capacityReservationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&omev1beta1.CapacityReservation{}, f.defaultInformer)
}

func (f *capacityReservationInformer) Lister() v1beta1.CapacityReservationLister {
	return v1beta1.NewCapacityReservationLister(f.Informer().GetIndexer())
}
