// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	apisomev1beta1 "github.com/sgl-project/ome/pkg/apis/ome/v1beta1"
	versioned "github.com/sgl-project/ome/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sgl-project/ome/pkg/client/informers/externalversions/internalinterfaces"
	omev1beta1 "github.com/sgl-project/ome/pkg/client/listers/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FineTunedWeightInformer provides access to a shared informer and lister for
// FineTunedWeights.
type FineTunedWeightInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() omev1beta1.FineTunedWeightLister
}

type fineTunedWeightInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewFineTunedWeightInformer constructs a new informer for FineTunedWeight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFineTunedWeightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFineTunedWeightInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFineTunedWeightInformer constructs a new informer for FineTunedWeight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFineTunedWeightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().FineTunedWeights().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().FineTunedWeights().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().FineTunedWeights().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().FineTunedWeights().Watch(ctx, options)
			},
		},
		&apisomev1beta1.FineTunedWeight{},
		resyncPeriod,
		indexers,
	)
}

func (f *fineTunedWeightInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFineTunedWeightInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *fineTunedWeightInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisomev1beta1.FineTunedWeight{}, f.defaultInformer)
}

func (f *fineTunedWeightInformer) Lister() omev1beta1.FineTunedWeightLister {
	return omev1beta1.NewFineTunedWeightLister(f.Informer().GetIndexer())
}
