// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisomev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	versioned "sigs.k8s.io/ome/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/ome/pkg/client/informers/externalversions/internalinterfaces"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/listers/ome/v1beta1"
)

// InferenceReplicaInformer provides access to a shared informer and lister for
// InferenceReplicas.
type InferenceReplicaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() omev1beta1.InferenceReplicaLister
}

type inferenceReplicaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInferenceReplicaInformer constructs a new informer for InferenceReplica type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInferenceReplicaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInferenceReplicaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInferenceReplicaInformer constructs a new informer for InferenceReplica type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInferenceReplicaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().InferenceReplicas(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().InferenceReplicas(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().InferenceReplicas(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().InferenceReplicas(namespace).Watch(ctx, options)
			},
		},
		&apisomev1beta1.InferenceReplica{},
		resyncPeriod,
		indexers,
	)
}

func (f *inferenceReplicaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInferenceReplicaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *inferenceReplicaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisomev1beta1.InferenceReplica{}, f.defaultInformer)
}

func (f *inferenceReplicaInformer) Lister() omev1beta1.InferenceReplicaLister {
	return omev1beta1.NewInferenceReplicaLister(f.Informer().GetIndexer())
}
