// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	versioned "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned"
	internalinterfaces "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/listers/ome/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// OciPostgresDBInstanceInformer provides access to a shared informer and lister for
// OciPostgresDBInstances.
type OciPostgresDBInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.OciPostgresDBInstanceLister
}

type ociPostgresDBInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewOciPostgresDBInstanceInformer constructs a new informer for OciPostgresDBInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewOciPostgresDBInstanceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredOciPostgresDBInstanceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredOciPostgresDBInstanceInformer constructs a new informer for OciPostgresDBInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredOciPostgresDBInstanceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().OciPostgresDBInstances().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().OciPostgresDBInstances().Watch(context.TODO(), options)
			},
		},
		&omev1beta1.OciPostgresDBInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *ociPostgresDBInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredOciPostgresDBInstanceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ociPostgresDBInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&omev1beta1.OciPostgresDBInstance{}, f.defaultInformer)
}

func (f *ociPostgresDBInstanceInformer) Lister() v1beta1.OciPostgresDBInstanceLister {
	return v1beta1.NewOciPostgresDBInstanceLister(f.Informer().GetIndexer())
}
