// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisomev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	versioned "sigs.k8s.io/ome/pkg/client/clientset/versioned"
	internalinterfaces "sigs.k8s.io/ome/pkg/client/informers/externalversions/internalinterfaces"
	omev1beta1 "sigs.k8s.io/ome/pkg/client/listers/ome/v1beta1"
)

// WorkloadClusterInformer provides access to a shared informer and lister for
// WorkloadClusters.
type WorkloadClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() omev1beta1.WorkloadClusterLister
}

type workloadClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewWorkloadClusterInformer constructs a new informer for WorkloadCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkloadClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkloadClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredWorkloadClusterInformer constructs a new informer for WorkloadCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkloadClusterInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().WorkloadClusters().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().WorkloadClusters().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().WorkloadClusters().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OmeV1beta1().WorkloadClusters().Watch(ctx, options)
			},
		},
		&apisomev1beta1.WorkloadCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *workloadClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkloadClusterInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workloadClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisomev1beta1.WorkloadCluster{}, f.defaultInformer)
}

func (f *workloadClusterInformer) Lister() omev1beta1.WorkloadClusterLister {
	return omev1beta1.NewWorkloadClusterLister(f.Informer().GetIndexer())
}
