{{- if .Values.command_a_vision_drcc.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: command-a-vision-drcc
  namespace: command-a-vision-drcc
spec:
  predictor:
    model:
      runtime: cohere-command-a-vision-drcc
      baseModel: command-a-vision-drcc
      protocolVersion: cohere
    minReplicas: {{ .Values.command_a_vision_drcc.minReplicas}}
    maxReplicas: {{ .Values.command_a_vision_drcc.maxReplicas}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: command-a-vision-drcc
{{- end }}