{{- if .Values.gpt_oss_120b.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: gpt-oss-120b
  namespace: gpt-oss-120b
spec:
  acceleratorSelector:
    acceleratorClass: nvidia-h100-2
  engine:
    minReplicas: {{ .Values.gpt_oss_120b.minReplicas}}
    maxReplicas: {{ .Values.gpt_oss_120b.maxReplicas}}
  model:
    apiGroup: ome.io
    kind: ClusterBaseModel
    name: gpt-oss-120b
  runtime:
    apiGroup: ome.io
    kind: ClusterServingRuntime
    name: vllm-gpt-oss-120b-mxfp4
  router:
    minReplicas: {{ .Values.gpt_oss_120b.router.minReplicas}}
    maxReplicas: {{ .Values.gpt_oss_120b.router.maxReplicas}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpt-oss-120b
{{- end }}