{{- if .Values.gpt_oss_120b.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: gpt-oss-120b
  namespace: gpt-oss-120b
spec:
  acceleratorSelector:
    acceleratorClass: nvidia-h100-2
  predictor:
    model:
      runtime: vllm-gpt-oss-120b-mxfp4
      baseModel: gpt-oss-120b
      protocolVersion: openai
    minReplicas: {{ .Values.gpt_oss_120b.minReplicas}}
    maxReplicas: {{ .Values.gpt_oss_120b.maxReplicas}}
  router:
    minReplicas: {{ .Values.gpt_oss_120b.minReplicas}}
    maxReplicas: {{ .Values.gpt_oss_120b.maxReplicas}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpt-oss-120b
{{- end }}