{{- if .Values.grok_4_1_fast_self_hosted.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: grok-4-1-fast-self-hosted
  namespace: grok-4-1-fast-self-hosted
spec:
  predictor:
    model:
      runtime: xai-grok-4-1-fast-rt
      baseModel:  grok-4-1-fast-self-hosted
      protocolVersion: xAI
    minReplicas: {{ .Values.grok_4_1_fast_self_hosted.minReplicas}}
    maxReplicas: {{ .Values.grok_4_1_fast_self_hosted.maxReplicas}}

---
apiVersion: v1
kind: Namespace
metadata:
  name: grok-4-1-fast-self-hosted

{{- end }}
