{{- if .Values.llama_guard_4_12b.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-guard-4-12b
  namespace: llama-guard-4-12b
spec:
  predictor:
    model:
      baseModel: llama-guard-4-12b
      protocolVersion: openAI
      runtime: vllm-llama-guard-4-12b
    minReplicas: {{ .Values.llama_guard_4_12b.minReplicas}}
    maxReplicas: {{ .Values.llama_guard_4_12b.maxReplicas}}

---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-guard-4-12b

{{- end }}
