{{- if index .Values "llama-3-1-405b-instruct-fp8-rdma" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama3-1-405b-instruct-fp8
  namespace: llama3-1-405b-instruct-fp8
spec:
  predictor:
    dnsPolicy: ClusterFirstWithHostNet
    hostNetwork: true
    model:
      runtime: vllm-serving-runtime-large-pp-rdma
      baseModel: llama-3-1-405b-instruct-fp8
      protocolVersion: openAI
    minReplicas: {{ index .Values "llama-3-1-405b-instruct-fp8-rdma" "minReplicas" }}
    maxReplicas: {{ index .Values "llama-3-1-405b-instruct-fp8-rdma" "maxReplicas" }}
{{- end }}