{{- if .Values.phi_3_mini_128k_instruct.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: phi-3-mini-128k-instruct
  namespace: phi-3-mini-128k-instruct
spec:
  predictor:
    {{- with .Values.phi_3_mini_128k_instruct.annotations }}
    annotations: {{ toYaml . | nindent 6 }}
    {{- end }}
    model:
      runtime: vllm-vision
      baseModel: phi-3-mini-128k-instruct
      protocolVersion: openAI
    minReplicas: {{ .Values.phi_3_mini_128k_instruct.maxReplicas}}
    maxReplicas: {{ .Values.phi_3_mini_128k_instruct.maxReplicas}}
    {{- with .Values.phi_3_mini_128k_instruct.affinity }}
    affinity: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.phi_3_mini_128k_instruct.tolerations }}
    tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.phi_3_mini_128k_instruct.topologySpreadConstraints }}
    topologySpreadConstraints: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.phi_3_mini_128k_instruct.volumes }}
    volumes: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.phi_3_mini_128k_instruct.scaleMetric }}
    scaleMetric: {{ toYaml . | nindent 6 }}
    {{- end }}

{{- end }}