apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ome.oracle.com_inferenceservices.yaml
  - ome.oracle.com_clusterservingruntimes.yaml
  - ome.oracle.com_servingruntimes.yaml
  - ome.oracle.com_clusterstoragecontainers.yaml
