apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alfred-e2e

resources:
  - resources.yaml

images:
  - name: alfred-e2e-placeholder
    newName: alfred-e2e-placeholder
    newTag: latest
