apiVersion: ome.io/v1beta1
kind: Organization
metadata:
    name: genai-openai-0001
spec:
  organizationId: ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva
  vendor: openai
  disabled: false
  secretRef:
    name: openai-admin-key
    key: OPENAI_ADMIN_API_KEY
    namespace: genai-openai
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-admin-key
  namespace: genai-openai
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
type: Opaque
immutable: true
data:
  OPENAI_ADMIN_API_KEY: c2stYWRtaW4teS16WV9STkpjLXpVaVFuM3hjelpNcXFjZlFNdlZ6NFdLSUdkWWk4dkpNd0gxYVRBaFBrYVBUYjFNNlQzQmxia0ZKa2NXeHlYUmVmUHdZMXVZMExnaXk5X18xSVFtbzZoMGFZVW9sMGtvQjRrYUQ0dkJwcEotZHdYa1hnQQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: genai-openai