apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: gpt-oss-20b
  namespace: gpt-oss-20b
spec:
  predictor:
    model:
      runtime: srt-gpt-oss-20b
      baseModel: gpt-oss-20b
      protocolVersion: openai
    minReplicas: 1
    maxReplicas: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpt-oss-20b