apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gpt-4-1-mini-2025-04-14
  labels:
    ome.io/oci-compartmentid: ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: ""
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "false"
    models.ome.io/internal: "false"
    models.ome.io/lifecycle-phase: "ACTIVE"
spec:
  disabled: false
  displayName: openai.gpt-4.1-mini-2025-04-14
  storage:
    storageUri: "vendor://openai/models/gpt-4-1-mini-2025-04-14"
  vendor: openai
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformer
    version: "1"
  modelArchitecture: OpenAIForCausalLM
  modelParameterSize: 1.8T
  modelCapabilities:
    - "CHAT"
  maxTokens: 1047576
