apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: srt-gemma-2-27b-it
spec:
  acceleratorRequirements:
    acceleratorClasses:
      - nvidia-a100-80gb-1
      - nvidia-a100-80gb-2
      - nvidia-a100-80gb-4
      - nvidia-a100-80gb-8
      - nvidia-a100-40gb-1
      - nvidia-a100-40gb-2
      - nvidia-a100-40gb-4
      - nvidia-a100-40gb-8
      - nvidia-h100-1
      - nvidia-h100-2
      - nvidia-h100-4
      - nvidia-h100-8
      - nvidia-a10-1
      - nvidia-a10-2
      - nvidia-a10-4
      - nvidia-h200-1
      - nvidia-h200-2
      - nvidia-h200-4
      - nvidia-h200-8
  disabled: false
  {{- if or .Values.commonAnnotations .Values.gemma_2_27b_it.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.gemma_2_27b_it.annotations }}
    {{ toYaml .Values.gemma_2_27b_it.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonLabels .Values.gemma_2_27b_it.labels }}
  labels:
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.gemma_2_27b_it.labels }}
    {{ toYaml .Values.gemma_2_27b_it.labels | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonTolerations .Values.gemma_2_27b_it.tolerations }}
  tolerations:
    {{- if .Values.commonTolerations }}
    {{ toYaml .Values.commonTolerations | nindent 4 }}
    {{- end }}
    {{- if .Values.gemma_2_27b_it.tolerations }}
    {{ toYaml .Values.gemma_2_27b_it.tolerations | nindent 4 }}
    {{- end }}
  {{- end }}
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    {{- if or (eq .Values.oci.realm "oc5") (eq .Values.oci.realm "oc6") }}
    - name: etc-pki
      hostPath:
        path: /etc/pki
        type: Directory
    {{- end }}
  {{ with .Values.gemma_2_27b_it }}
  affinity: {{ .affinity | toYaml | nindent 4 }}
  {{ end }}
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.42.0.dev0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      autoSelect: true
      modelArchitecture: Gemma2ForCausalLM
      version: "1.0.0"
      priority: 1
      acceleratorConfig:
        nvidia-a100-80gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-80gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-80gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-80gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a100-40gb-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a100-40gb-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a100-40gb-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-a100-40gb-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-h100-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h100-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h100-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h100-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
        nvidia-a10-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-a10-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-a10-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-1:
          tensorParallelismOverride:
            tensorParallelSize: 1
        nvidia-h200-2:
          tensorParallelismOverride:
            tensorParallelSize: 2
        nvidia-h200-4:
          tensorParallelismOverride:
            tensorParallelSize: 4
        nvidia-h200-8:
          tensorParallelismOverride:
            tensorParallelSize: 8
  modelSizeRange:
    min: 24.3B
    max: 29.7B
  protocolVersions:
    - openAI
  schedulerName: {{ .Values.commonSchedulerName }}
  containers:
    - name: ome-container
      image: {{ .Values.gemma_2_27b_it.image.repository | default .Values.sglang.commonImage.repository }}:{{ .Values.gemma_2_27b_it.image.tag | default .Values.sglang.commonImage.tag }}
      ports:
        - containerPort: {{ .Values.sglang.port }}
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          python3 -m sglang.launch_server \
          --host=0.0.0.0 \
          --port={{ .Values.sglang.port }} \
          --model-path "$MODEL_PATH" \
          --tp-size 2 \
          --mem-fraction-static 0.9 \
          --log-requests \
          --enable-metrics 
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 10
          memory: 60Gi
          nvidia.com/gpu: 2
        limits:
          cpu: 10
          memory: 60Gi
          nvidia.com/gpu: 2

      readinessProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 200

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
  engineConfig:
    schedulerName: {{ .Values.commonSchedulerName }}
    {{- if or .Values.commonAnnotations .Values.gemma_2_27b_it.annotations }}
    annotations:
        {{- if .Values.commonAnnotations }}
        {{ toYaml .Values.commonAnnotations | nindent 6 }}
        {{- end }}
        {{- if .Values.gemma_2_27b_it.annotations }}
        {{ toYaml .Values.gemma_2_27b_it.annotations | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.commonLabels .Values.gemma_2_27b_it.labels }}
    labels:
        {{- if .Values.commonLabels }}
        {{ toYaml .Values.commonLabels | nindent 6 }}
        {{- end }}
        {{- if .Values.gemma_2_27b_it.labels }}
        {{ toYaml .Values.gemma_2_27b_it.labels | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.commonTolerations .Values.gemma_2_27b_it.tolerations }}
    tolerations:
        {{- if .Values.commonTolerations }}
        {{ toYaml .Values.commonTolerations | nindent 6 }}
        {{- end }}
        {{- if .Values.gemma_2_27b_it.tolerations }}
        {{ toYaml .Values.gemma_2_27b_it.tolerations | nindent 6 }}
        {{- end }}
      {{- end }}
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
        {{- if or (eq .Values.oci.realm "oc5") (eq .Values.oci.realm "oc6") }}
      - name: etc-pki
        hostPath:
          path: /etc/pki
          type: Directory
        {{- end }}
      {{ with .Values.gemma_2_27b_it }}
    affinity: {{ .affinity | toYaml | nindent 6 }}
      {{ end }}
    runner:
      name: ome-container
      image: {{ .Values.gemma_2_27b_it.image.repository | default .Values.sglang.commonImage.repository }}:{{ .Values.gemma_2_27b_it.image.tag | default .Values.sglang.commonImage.tag }}
      ports:
        - containerPort: {{ .Values.sglang.port }}
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          python3 -m sglang.launch_server \
          --host=0.0.0.0 \
          --port={{ .Values.sglang.port }} \
          --model-path "$MODEL_PATH" \
          --tp-size 2 \
          --mem-fraction-static 0.9 \
          --log-requests \
          --enable-metrics
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 10
          memory: 60Gi
          nvidia.com/gpu: 2
        limits:
          cpu: 10
          memory: 60Gi
          nvidia.com/gpu: 2

      readinessProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 200

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
