apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: srt-gpt-oss-120b
spec:
  disabled: false
  {{- if or .Values.commonAnnotations .Values.gpt_oss_120b_bf16.annotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | nindent 6 }}
    {{- end }}
    {{- if .Values.gpt_oss_120b_bf16.annotations }}
    {{ toYaml .Values.gpt_oss_120b_bf16.annotations | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonLabels .Values.gpt_oss_120b_bf16.labels }}
  labels:
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 6 }}
    {{- end }}
    {{- if .Values.gpt_oss_120b_bf16.labels }}
    {{ toYaml .Values.gpt_oss_120b_bf16.labels | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if or .Values.commonTolerations .Values.gpt_oss_120b_bf16.tolerations }}
  tolerations:
    {{- if .Values.commonTolerations }}
    {{ toYaml .Values.commonTolerations | nindent 6 }}
    {{- end }}
    {{- if .Values.gpt_oss_120b_bf16.tolerations }}
    {{ toYaml .Values.gpt_oss_120b_bf16.tolerations | nindent 6 }}
    {{- end }}
  {{- end }}
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    {{- if or (eq .Values.oci.realm "oc5") (eq .Values.oci.realm "oc6") }}
    - name: etc-pki
      hostPath:
        path: /etc/pki
        type: Directory
    {{- end }}
  {{ with .Values.gpt_oss_120b_bf16 }}
  affinity: {{ .affinity | toYaml | nindent 6 }}
  {{ end }}
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.55.0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: GptOssForCausalLM
      autoSelect: true
      priority: 1
  modelSizeRange:
    min: 115B
    max: 125B
  protocolVersions:
    - openAI
  schedulerName: {{ .Values.commonSchedulerName }}
  containers:
    - name: ome-container
      image: {{ .Values.gpt_oss_120b_bf16.image.repository | default .Values.sglang.commonImage.repository }}:{{ .Values.gpt_oss_120b_bf16.image.tag | default .Values.sglang.commonImage.tag }}
      ports:
        - containerPort: {{ .Values.sglang.port }}
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          python3 -m sglang.launch_server \
          --host=0.0.0.0 \
          --port={{ .Values.sglang.port }} \
          --enable-metrics \
          --log-requests \
          --model-path="$MODEL_PATH" \
          --tp 2 \
          --tool-call-parser=gpt-oss \
          --reasoning-parser=gpt-oss \
          --context-length=131072
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: 2
        limits:
          cpu: 30
          memory: 100Gi
          nvidia.com/gpu: 2

      readinessProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 200

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
