apiVersion: v1
kind: Namespace
metadata:
  name: sglang-deepseek-r1
---

apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: srt-deepseek-r1
  namespace: sglang-deepseek-r1
spec:
  replicas: 2
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 1
      maxUnavailable: 0
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: srt-leader
      spec:
        nodeSelector:
          oci.oraclecloud.com/rdma.authenticated: "16"
          oci.oraclecloud.com/rdma.mlx_issues: "0"
          oke.oraclecloud.com/pool.mode: cluster-network
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
          - name: srt-deepseek-r1-leader
            image: fra.ocir.io/idqj093njucb/official-sgl:v0.4.1.local-1
            resources:
              limits:
                nvidia.com/gpu: "8"
              requests:
                nvidia.com/gpu: "8"
            command:
              - sh
              - -c
              - "python3 -m sglang.launch_server --host 0.0.0.0 --port 8080 --model-path /models --tp 16 --nccl-init $(LWS_LEADER_ADDRESS):5000 --nnodes 2 --node-rank 0 --trust-remote-code --enable-metrics"
            env:
              - name: NCCL_NET_PLUGIN
                value: none
              - name: NCCL_DEBUG
                value: INFO
              - name: NCCL_CROSS_NIC
                value: '2'
              - name: NCCL_SOCKET_NTHREADS
                value: '16'
              - name: NCCL_CUMEM_ENABLE
                value: '0'
              - name: NCCL_IB_SPLIT_DATA_ON_QPS
                value: '0'
              - name: NCCL_IB_QPS_PER_CONNECTION
                value: '16'
              - name: NCCL_IB_GID_INDEX
                value: '3'
              - name: NCCL_IB_HCA
                value: "=mlx5_0,mlx5_1,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7,mlx5_8,mlx5_9,mlx5_10,mlx5_12,mlx5_13,mlx5_14,mlx5_15,mlx5_16,mlx5_17"
              - name: NCCL_IB_TC
                value: '41'
              - name: NCCL_IB_SL
                value: '0'
              - name: NCCL_IB_TIMEOUT
                value: '22'
              - name: HCOLL_ENABLE_MCAST_ALL
                value: '0'
              - name: coll_hcoll_enable
                value: '0'
              - name: UCX_TLS
                value: tcp
              - name: UCX_NET_DEVICES
                value: eth0
              - name: RX_QUEUE_LEN
                value: '8192'
              - name: IB_RX_QUEUE_LEN
                value: '8192'
              - name: NCCL_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IGNORE_CPU_AFFINITY
                value: '1'
              - name: GLOO_SOCKET_IFNAME
                value: eth0
            securityContext:
              capabilities:
                add:
                  - IPC_LOCK
                  - CAP_SYS_ADMIN
              privileged: true
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - mountPath: /models
                name: model-storage
              - mountPath: /dev/infiniband
                name: devinf
              - mountPath: /tmp/ray
                name: log-volume
            readinessProbe:
              httpGet:
                path: /health_generate
                port: 8080
              failureThreshold: 3
              successThreshold: 1
              periodSeconds: 60
              timeoutSeconds: 200

            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              failureThreshold: 5
              successThreshold: 1
              periodSeconds: 60
              timeoutSeconds: 60

            startupProbe:
              httpGet:
                path: /health_generate
                port: 8080
              failureThreshold: 300
              successThreshold: 1
              periodSeconds: 6
              initialDelaySeconds: 60
              timeoutSeconds: 30
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
        - name: model-storage
          hostPath:
            path: /raid/models/deepseek-ai/deepseek-r1
            type: Directory
        - hostPath:
            path: /dev/infiniband
          name: devinf
        - emptyDir: {}
          name: log-volume
    workerTemplate:
      metadata: {}
      spec:
        nodeSelector:
          oci.oraclecloud.com/rdma.authenticated: "16"
          oci.oraclecloud.com/rdma.mlx_issues: "0"
          oke.oraclecloud.com/pool.mode: cluster-network
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
          - name: srt-deepseek-r1-worker
            image: fra.ocir.io/idqj093njucb/official-sgl:v0.4.1.local-1
            command:
              - sh
              - -c
              - "python3 -m sglang.launch_server --host 0.0.0.0 --port 8080 --model-path /models --tp 16 --nccl-init $(LWS_LEADER_ADDRESS):5000 --nnodes 2 --node-rank 1 --trust-remote-code --enable-metrics"
            resources:
              limits:
                nvidia.com/gpu: "8"
              requests:
                nvidia.com/gpu: "8"
            env:
              - name: NCCL_NET_PLUGIN
                value: none
              - name: NCCL_DEBUG
                value: INFO
              - name: NCCL_CROSS_NIC
                value: '2'
              - name: NCCL_SOCKET_NTHREADS
                value: '16'
              - name: NCCL_CUMEM_ENABLE
                value: '0'
              - name: NCCL_IB_SPLIT_DATA_ON_QPS
                value: '0'
              - name: NCCL_IB_QPS_PER_CONNECTION
                value: '16'
              - name: NCCL_IB_GID_INDEX
                value: '3'
              - name: NCCL_IB_HCA
                value: "=mlx5_0,mlx5_1,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7,mlx5_8,mlx5_9,mlx5_10,mlx5_12,mlx5_13,mlx5_14,mlx5_15,mlx5_16,mlx5_17"
              - name: NCCL_IB_TC
                value: '41'
              - name: NCCL_IB_SL
                value: '0'
              - name: NCCL_IB_TIMEOUT
                value: '22'
              - name: HCOLL_ENABLE_MCAST_ALL
                value: '0'
              - name: coll_hcoll_enable
                value: '0'
              - name: UCX_TLS
                value: tcp
              - name: UCX_NET_DEVICES
                value: eth0
              - name: RX_QUEUE_LEN
                value: '8192'
              - name: IB_RX_QUEUE_LEN
                value: '8192'
              - name: NCCL_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IGNORE_CPU_AFFINITY
                value: '1'
              - name: GLOO_SOCKET_IFNAME
                value: eth0
            securityContext:
              capabilities:
                add:
                  - IPC_LOCK
                  - CAP_SYS_ADMIN
              privileged: true
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - mountPath: /models
                name: model-storage
              - mountPath: /dev/infiniband
                name: devinf
              - mountPath: /tmp/ray
                name: log-volume
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
        - name: model-storage
          hostPath:
            path: /raid/models/deepseek-ai/deepseek-r1
            type: Directory
        - hostPath:
            path: /dev/infiniband
          name: devinf
        - emptyDir: {}
          name: log-volume
---
apiVersion: v1
kind: Service
metadata:
  name: srt-deepseek-r1-leader
  namespace: sglang-deepseek-r1
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    leaderworkerset.sigs.k8s.io/name: srt-deepseek-r1
    role: srt-leader
  type: LoadBalancer
  loadBalancerIP: 147.154.172.85
