apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: command-a-vision-drcc
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: "cohere-command-1-trt"
    models.ome.io/category: "LARGE"
    models.ome.io/experimental: "false"
    models.ome.io/internal: "false"
    models.ome.io/lifecycle-phase: "ACTIVE"
    ome.io/base-model-decryption-key-name: "command_3"
    ome.io/base-model-decryption-secret-name: "command_3-dek"
spec:
  disabled: false
  displayName: cohere.command-a-vision
  storage:
    storageUri: oci://n/idqj093njucb/b/partner-models/o/cohere/command-a-vision
    path: /raid/models/cohere/command-a-vision
  vendor: cohere
  version: "1.0"
  compartmentID: ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva
  # keep trt structure for now
  modelFormat:
    name: tensorrtllm
    version: 'v0.8.0'
  modelFramework:
    name: tensorrtllm
    version: 'v0.8.0'
  modelArchitecture: CohereForCausalLM
  modelParameterSize: 111B
  modelCapabilities:
    - "CHAT"
  maxTokens: 256000
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: SMALL_COHERE_4
          quotaUnit: 1
          default: true
    internalName: "command-a-vision"
    type: "Serving"
