apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: cohere-embed
  labels:
    genai-managed-base-model-v1beta1: "true"
  annotations:
    models.ome.io/runtime: "cohere-embed-v1"
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "false"
    models.ome.io/internal: "false"
    models.ome.io/lifecycle-phase: "BASEMODEL_LIFE_CYCLE_PHASE_DEPRECATED"
    ome.io/base-model-decryption-key-name: "embed"
    ome.io/base-model-encryption-secret-name: "embed-dek"
spec:
  compartmentID: ocid1.compartment.oc1..aaaaaaaazq
  disabled: false
  displayName: cohere.embed-english-light-v2.0
  storage:
    storageUri: oci://n/idlsnvn0f2is/b/partner-models/o/cohere/e355m-3.1.0-ft-triton
    path: /raid/models/cohere/e355m-3.1.0-ft-triton
  vendor: cohere
  version: "2.0"
  modelFormat:
    name: onnxruntime
    version: '1'
  modelFramework:
    name: onnx
    version: '1'
  modelArchitecture: CohereForCasualLM
  modelParameterSize: 0.76B
  modelCapabilities:
    - "TEXT_EMBEDDINGS"
  maxTokens: 4096
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: EMBED_COHERE
          quotaUnit: 1
          default: true
    internalName: "e355m-3.1.0-ft-triton"
    type: "Serving"