{{- if index .Values "grok-4-3" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: grok-4-3
  labels:
    {{ include "proxy-models-importer.genaiModelLabels" (dict "root" $ "model" "grok-4-3") | nindent 4 }}
  annotations:
    {{ include "proxy-models-importer.genaiModelAnnotations" (dict "root" $ "model" "grok-4-3") | nindent 4 }}
spec:
  compartmentID: {{ .Values.compartmentID }}
  disabled: false
  displayName: xai.grok-4.3
  storage:
    storageUri: "vendor://xai/models/{{ index .Values "grok-4-3" "osPrefixOverride" }}"
  vendor: {{ index .Values "grok-4-3" "vendor" }}
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformer
    version: "1"
  modelArchitecture: xAiForCausalLM
  modelParameterSize: 1.7T
  modelCapabilities:
    - "CHAT"
  apiCapabilities:
    - "OCI_GENERIC_CHAT_REQUEST"
    - "OPENAI_V1_CHAT_COMPLETIONS"
    - "OPENAI_V1_RESPONSES"
  maxTokens: 2000000
{{- end }}