apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: ome
data:
  multinodeProber: |-
    {
        "image" : "{{.Values.ome.multinodeProber.image}}:{{.Values.ome.multinodeProber.tag}}",
        "memoryRequest": "{{.Values.ome.multinodeProber.memoryRequest}}",
        "memoryLimit": "{{.Values.ome.multinodeProber.memoryLimit}}",
        "cpuRequest": "{{.Values.ome.multinodeProber.cpuRequest}}",
        "cpuLimit": "{{.Values.ome.multinodeProber.cpuLimit}}",
        "startupFailureThreshold": "{{.Values.ome.multinodeProber.startupFailureThreshold}}",
        "startupPeriodSeconds": "{{.Values.ome.multinodeProber.startupPeriodSeconds}}",
        "startupTimeoutSeconds": "{{.Values.ome.multinodeProber.startupTimeoutSeconds}}",
        "startupInitialDelaySeconds": "{{.Values.ome.multinodeProber.startupInitialDelaySeconds}}"
    }
  ingress: |-
    {
        "ingressGateway" : "{{ .Values.ome.controller.ingressGateway.ingressGateway.gateway }}",
        "ingressService" : "{{ .Values.ome.controller.ingressGateway.ingressGateway.gatewayService }}",
        "localGateway" : "{{ .Values.ome.controller.ingressGateway.localGateway.gateway }}",
        "localGatewayService" : "{{ .Values.ome.controller.ingressGateway.localGateway.gatewayService }}",
        "ingressClassName" : "{{ .Values.ome.controller.ingressGateway.ingressGateway.className }}",
        "ingressDomain"  : "{{ .Values.ome.controller.ingressGateway.domain }}",
        "domainTemplate": "{{ .Values.ome.controller.ingressGateway.domainTemplate }}",
        "urlScheme": "{{ .Values.ome.controller.ingressGateway.urlScheme }}",
        "disableIstioVirtualHost": {{ .Values.ome.controller.ingressGateway.disableIstioVirtualHost }}
    }

  logger: |-
    {
        "image" : "ome/agent:latest",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "defaultUrl": "http://default-broker"
    }

  agent: |-
    {
        "image" : "ome/agent:latest",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }

  ociEtc: |-
    {
        "region" : "{{ .Values.ome.ociETC.region }}",
        "serviceCompartmentId": "{{ .Values.ome.ociETC.serviceCompartmentId }}",
        "serviceTenancyId": "{{ .Values.ome.ociETC.serviceTenancyId }}",
        "stage": "{{ .Values.ome.ociETC.stage }}",
        "realm": "{{ .Values.ome.ociETC.realm }}",
        "applicationStage": "{{ .Values.ome.ociETC.applicationStage }}",
        "publicDomainName": "{{ .Values.ome.ociETC.publicDomainName }}",
        "internalDomainName": "{{ .Values.ome.ociETC.internalDomainName }}",
        "airportCode": "{{ .Values.ome.ociETC.airportCode }}",
        "adNumberName": "{{ .Values.ome.ociETC.adNumberName }}",
        "namespace": "{{ .Values.ome.ociETC.namespace }}"
    }


  deploy: |-
    {
      "defaultDeploymentMode": "{{ .Values.ome.controller.deploymentMode }}"
    }

  metricsAggregator: |-
    {
      "enableMetricAggregation": "{{ .Values.ome.metricsaggregator.enableMetricAggregation }}",
      "enablePrometheusScraping" : "{{ .Values.ome.metricsaggregator.enablePrometheusScraping }}"
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dedicatedaicluster-config
  namespace: ome
data:
  reservationJob: |-
    {
      "image": "{{ .Values.ome.controller.image }}:{{ .Values.ome.controller.tag }}",
      "creationFailedTimeThresholdSecond" : 30
    }
  dacReconcilePolicy: |-
    {
      "reconcileFailedLifecycleState": false
    }
