{{- if .Values.google.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.google.namespace}}
---
apiVersion: ome.io/v1beta1
kind: Organization
metadata:
  name: genai-google-0001
spec:
  organizationId: {{.Values.ome.ociETC.serviceCompartmentId}}
  vendor: google
  disabled: false
{{- end }}