apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ome-vault-secrets-csi
  namespace: ome
spec:
  provider: oci
  parameters:
    secrets: |
      - name: GoogleSaFile
        stage: CURRENT
        fileName: google-sa-file
    authType: instance
    vaultId: {{ .Values.ome.secrets.vaultId }}