apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ome-vault-secrets-csi
  namespace: ome
spec:
  provider: oci
  parameters:
    secrets: |
{{- if .Values.google.enabled }}
      - name: GoogleSaFile
        stage: CURRENT
        fileName: google-sa-file
{{- end }}
{{- if .Values.openai.enabled }}
      - name: OpenAiAdminKey
        stage: CURRENT
        fileName: openai-admin-key
{{- end }}
{{- if .Values.openaiProxy.enabled }}
      - name: OpenAiProxyAdminKey
        stage: CURRENT
        fileName: openai-proxy-admin-key
{{- end }}
{{- if .Values.xai.enabled }}
      - name: XaiAdminKey
        stage: CURRENT
        fileName: xai-admin-key
{{- end }}
    authType: instance
    vaultId: {{ .Values.ome.secrets.vaultId }}
