apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ome-model-agent-daemonset
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: 
      app.kubernetes.io/component: "ome-model-agent-daemonset"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "ome-model-agent-daemonset"
        logging-forward: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.modelAgent.health.port }}"
        prometheus.io/path: "/metrics"
    spec:
      priorityClassName: {{ .Values.modelAgent.priorityClassName }}
      serviceAccountName: {{ .Values.modelAgent.serviceAccountName }}
      affinity:
        {{- toYaml .Values.modelAgent.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.modelAgent.nodeSelector | nindent 8 }}
      volumes:
      - name: host-models
        hostPath:
          path: {{ .Values.modelAgent.hostPath }}
          type: Directory
      {{- if or (eq .Values.ome.ociETC.realm "oc5") (eq .Values.ome.ociETC.realm "oc6") }}
      - name: etc-pki
        hostPath:
          path: /etc/pki
          type: Directory
      {{- end }}
      containers:
      - name: model-agent
        image: "{{ .Values.modelAgent.image.repository }}:{{ .Values.modelAgent.image.tag }}"
        imagePullPolicy: {{ .Values.modelAgent.image.pullPolicy }}
        ports:
        - name: metrics
          containerPort: {{ .Values.modelAgent.health.port }}
          protocol: TCP
        args:
        - --models-root-dir
        - {{ .Values.modelAgent.hostPath }}
        - --num-download-worker
        - '2'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: INSTANCE_TYPE_MAP
          valueFrom:
            configMapKeyRef:
              name: model-agent-config-map
              key: instance-type-map
        {{- if or (eq .Values.ome.ociETC.realm "oc5") (eq .Values.ome.ociETC.realm "oc6") }}
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        {{- end }}
        volumeMounts:
        - name: host-models
          readOnly: false
          mountPath: {{ .Values.modelAgent.hostPath }}
        {{- if or (eq .Values.ome.ociETC.realm "oc5") (eq .Values.ome.ociETC.realm "oc6") }}
        - name: etc-pki
          mountPath: /etc/pki
          readOnly: true
        {{- end }}
        startupProbe:
          httpGet:
            path: /livez
            port: {{ .Values.modelAgent.health.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /livez
            port: {{ .Values.modelAgent.health.port }}
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.modelAgent.health.port }}
          periodSeconds: 10
        {{- if .Values.modelAgent.resources }}
        resources:
          {{- toYaml .Values.modelAgent.resources | nindent 10 }}
        {{- end }}   
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists  
          effect: NoSchedule
