apiVersion: v1
kind: PersistentVolume
metadata:
  name: ome-model-agent-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: {{ .Values.modelDownload.hostPath }}
    type: {{ .Values.modelDownload.hostPathType }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ome-model-agent-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 999Gi
