apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama3-1-405b-instruct-fp8-pp
  namespace: default
spec:
  predictor:
    model:
      runtime: vllm-serving-runtime-large-pp
      baseModel: llama-3-1-405b-instruct-fp8
      protocolVersion: openAI
    minReplicas: 2
    maxReplicas: 2
