{{- if .Values.llama_3_2_90b_vision_instruct.enabled }}
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-2-90b-vision
  namespace: llama-3-2-90b-vision
spec:
  predictor:
    {{- with .Values.llama_3_2_90b_vision_instruct.annotations }}
    annotations: {{ toYaml . | nindent 6 }}
    {{- end }}
    model:
      runtime: vllm-llama-3-2-90b
      baseModel: llama-3-2-90b-vision-instruct
      protocolVersion: openAI
    minReplicas: {{ .Values.llama_3_2_90b_vision_instruct.maxReplicas}}
    maxReplicas: {{ .Values.llama_3_2_90b_vision_instruct.maxReplicas}}
    {{- with .Values.llama_3_2_90b_vision_instruct.affinity }}
    affinity: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.llama_3_2_90b_vision_instruct.tolerations }}
    tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.llama_3_2_90b_vision_instruct.topologySpreadConstraints }}
    topologySpreadConstraints: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.llama_3_2_90b_vision_instruct.volumes }}
    volumes: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.llama_3_2_90b_vision_instruct.scaleMetric }}
    scaleMetric: {{ toYaml . | nindent 6 }}
    {{- end }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: llama-3-2-90b-vision

{{- end }}
