{{- if index .Values "gemini-3-flash-preview" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: gemini-3-flash-preview
  labels:
    genai-managed-base-model-v1beta1: "true"
    genai-model-deprecated-date: "{{ index .Values "gemini-3-flash-preview" "timeDeprecated" }}"
    genai-model-on-demand-retired-date: "{{ index .Values "gemini-3-flash-preview" "timeOnDemandRetired" }}"
    genai-model-dedicated-retired-date: "{{ index .Values "gemini-3-flash-preview" "timeDedicatedRetired" }}"
  annotations:
    models.ome.io/runtime: ""
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "{{ index .Values "gemini-3-flash-preview" "isExperimental" }}"
    models.ome.io/internal: "{{ index .Values "gemini-3-flash-preview" "isInternal" }}"
    models.ome.io/lifecycle-phase: "{{ index .Values "gemini-3-flash-preview" "lifecyclePhase" }}"
spec:
  compartmentID: {{ .Values.compartmentID }}
  disabled: false
  displayName: google.gemini-3-flash-preview
  storage:
    storageUri: "vendor://google/models/{{ index .Values "gemini-3-flash-preview" "osPrefixOverride" }}"
  vendor: {{ index .Values "gemini-3-flash-preview" "vendor" }}
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformer
    version: "1"
  modelArchitecture: GeminiForCausalLM
  modelParameterSize: 1.8T
  modelCapabilities:
    - "CHAT"
  maxTokens: 1048576
  additionalMetadata:
    image-text-to-text: "{{ index .Values "gemini-3-flash-preview" "enableImageInput" }}"
{{- end }} 