apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: opensource-ome-controller-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opensource-ome-controller-manager
  name: opensource-ome-controller-manager
