# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_keda_config import V1beta1KedaConfig


class TestV1beta1KedaConfig(unittest.TestCase):
    """V1beta1KedaConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1KedaConfig:
        """Test V1beta1KedaConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1KedaConfig`
        """
        model = V1beta1KedaConfig()
        if include_optional:
            return V1beta1KedaConfig(
                custom_prom_query = '',
                enable_keda = True,
                prom_server_address = '',
                scaling_operator = '',
                scaling_threshold = ''
            )
        else:
            return V1beta1KedaConfig(
        )
        """

    def testV1beta1KedaConfig(self):
        """Test V1beta1KedaConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
