# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_worker_pod_spec import V1beta1WorkerPodSpec


class TestV1beta1WorkerPodSpec(unittest.TestCase):
    """V1beta1WorkerPodSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1WorkerPodSpec:
        """Test V1beta1WorkerPodSpec
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1WorkerPodSpec`
        """
        model = V1beta1WorkerPodSpec()
        if include_optional:
            return V1beta1WorkerPodSpec(
                affinity = None,
                annotations = {
                    'key' : ''
                    },
                containers = [
                    None
                    ],
                dns_policy = '',
                host_ipc = True,
                host_network = True,
                image_pull_secrets = [
                    None
                    ],
                labels = {
                    'key' : ''
                    },
                node_selector = {
                    'key' : ''
                    },
                scheduler_name = '',
                size = 56,
                tolerations = [
                    None
                    ],
                volumes = [
                    None
                    ]
            )
        else:
            return V1beta1WorkerPodSpec(
                containers = [
                    None
                    ],
        )
        """

    def testV1beta1WorkerPodSpec(self):
        """Test V1beta1WorkerPodSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
