# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_metric_config import V1beta1MetricConfig


class TestV1beta1MetricConfig(unittest.TestCase):
    """V1beta1MetricConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1MetricConfig:
        """Test V1beta1MetricConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1MetricConfig`
        """
        model = V1beta1MetricConfig()
        if include_optional:
            return V1beta1MetricConfig(
                goal = '',
                name = ''
            )
        else:
            return V1beta1MetricConfig(
                goal = '',
                name = '',
        )
        """

    def testV1beta1MetricConfig(self):
        """Test V1beta1MetricConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
