# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_pod_group_policy import V1beta1PodGroupPolicy


class TestV1beta1PodGroupPolicy(unittest.TestCase):
    """V1beta1PodGroupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1PodGroupPolicy:
        """Test V1beta1PodGroupPolicy
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1PodGroupPolicy`
        """
        model = V1beta1PodGroupPolicy()
        if include_optional:
            return V1beta1PodGroupPolicy(
                coscheduling = ome.models.v1beta1/coscheduling_pod_group_policy_config.v1beta1.CoschedulingPodGroupPolicyConfig(
                    schedule_timeout_seconds = 56, )
            )
        else:
            return V1beta1PodGroupPolicy(
        )
        """

    def testV1beta1PodGroupPolicy(self):
        """Test V1beta1PodGroupPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
