# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_component_status_spec import V1beta1ComponentStatusSpec


class TestV1beta1ComponentStatusSpec(unittest.TestCase):
    """V1beta1ComponentStatusSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ComponentStatusSpec:
        """Test V1beta1ComponentStatusSpec
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1ComponentStatusSpec`
        """
        model = V1beta1ComponentStatusSpec()
        if include_optional:
            return V1beta1ComponentStatusSpec(
                address = None,
                latest_created_revision = '',
                latest_ready_revision = '',
                latest_rolledout_revision = '',
                previous_rolledout_revision = '',
                rest_url = None,
                traffic = [
                    None
                    ],
                url = None
            )
        else:
            return V1beta1ComponentStatusSpec(
        )
        """

    def testV1beta1ComponentStatusSpec(self):
        """Test V1beta1ComponentStatusSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
