# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_model_config import V1beta1ModelConfig


class TestV1beta1ModelConfig(unittest.TestCase):
    """V1beta1ModelConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ModelConfig:
        """Test V1beta1ModelConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1ModelConfig`
        """
        model = V1beta1ModelConfig()
        if include_optional:
            return V1beta1ModelConfig(
                input_model = '',
                output_model = ome.models.v1beta1/storage_spec.v1beta1.StorageSpec(
                    key = '', 
                    parameters = {
                        'key' : ''
                        }, 
                    path = '', 
                    schema_path = '', 
                    storage_uri = '', )
            )
        else:
            return V1beta1ModelConfig(
        )
        """

    def testV1beta1ModelConfig(self):
        """Test V1beta1ModelConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
