# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_service_metadata import V1beta1ServiceMetadata


class TestV1beta1ServiceMetadata(unittest.TestCase):
    """V1beta1ServiceMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ServiceMetadata:
        """Test V1beta1ServiceMetadata
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1ServiceMetadata`
        """
        model = V1beta1ServiceMetadata()
        if include_optional:
            return V1beta1ServiceMetadata(
                engine = '',
                gpu_count = 56,
                gpu_type = '',
                version = ''
            )
        else:
            return V1beta1ServiceMetadata(
                engine = '',
                gpu_count = 56,
                gpu_type = '',
                version = '',
        )
        """

    def testV1beta1ServiceMetadata(self):
        """Test V1beta1ServiceMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
