# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_inference_graph_status import V1beta1InferenceGraphStatus


class TestV1beta1InferenceGraphStatus(unittest.TestCase):
    """V1beta1InferenceGraphStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1InferenceGraphStatus:
        """Test V1beta1InferenceGraphStatus
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1InferenceGraphStatus`
        """
        model = V1beta1InferenceGraphStatus()
        if include_optional:
            return V1beta1InferenceGraphStatus(
                annotations = {
                    'key' : ''
                    },
                conditions = [
                    None
                    ],
                observed_generation = 56,
                url = None
            )
        else:
            return V1beta1InferenceGraphStatus(
        )
        """

    def testV1beta1InferenceGraphStatus(self):
        """Test V1beta1InferenceGraphStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
