# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_hyperparameter_tuning_config import (
    V1beta1HyperparameterTuningConfig,
)


class TestV1beta1HyperparameterTuningConfig(unittest.TestCase):
    """V1beta1HyperparameterTuningConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1HyperparameterTuningConfig:
        """Test V1beta1HyperparameterTuningConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1HyperparameterTuningConfig`
        """
        model = V1beta1HyperparameterTuningConfig()
        if include_optional:
            return V1beta1HyperparameterTuningConfig(
                max_trials = 56,
                method = '',
                metric = ome.models.v1beta1/metric_config.v1beta1.MetricConfig(
                    goal = '', 
                    name = '', ),
                parameters = None
            )
        else:
            return V1beta1HyperparameterTuningConfig(
                method = '',
                metric = ome.models.v1beta1/metric_config.v1beta1.MetricConfig(
                    goal = '', 
                    name = '', ),
                parameters = None,
        )
        """

    def testV1beta1HyperparameterTuningConfig(self):
        """Test V1beta1HyperparameterTuningConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
