# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_project import V1beta1Project


class TestV1beta1Project(unittest.TestCase):
    """V1beta1Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1Project:
        """Test V1beta1Project
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1Project`
        """
        model = V1beta1Project()
        if include_optional:
            return V1beta1Project(
                api_version = '',
                kind = '',
                metadata = None,
                spec = ome.models.v1beta1/project_spec.v1beta1.ProjectSpec(
                    config = {
                        'key' : ''
                        }, 
                    description = '', 
                    name = '', 
                    organization_ref = ome.models.v1beta1/cross_reference.v1beta1.CrossReference(
                        name = '', 
                        namespace = '', ), ),
                status = ome.models.v1beta1/project_status.v1beta1.ProjectStatus(
                    conditions = [
                        None
                        ], 
                    creation_time = None, 
                    last_updated_time = None, 
                    project_id = '', )
            )
        else:
            return V1beta1Project(
                spec = ome.models.v1beta1/project_spec.v1beta1.ProjectSpec(
                    config = {
                        'key' : ''
                        }, 
                    description = '', 
                    name = '', 
                    organization_ref = ome.models.v1beta1/cross_reference.v1beta1.CrossReference(
                        name = '', 
                        namespace = '', ), ),
        )
        """

    def testV1beta1Project(self):
        """Test V1beta1Project"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
