# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_project_spec import V1beta1ProjectSpec


class TestV1beta1ProjectSpec(unittest.TestCase):
    """V1beta1ProjectSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ProjectSpec:
        """Test V1beta1ProjectSpec
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1ProjectSpec`
        """
        model = V1beta1ProjectSpec()
        if include_optional:
            return V1beta1ProjectSpec(
                config = {
                    'key' : ''
                    },
                description = '',
                name = '',
                organization_ref = ome.models.v1beta1/cross_reference.v1beta1.CrossReference(
                    name = '', 
                    namespace = '', )
            )
        else:
            return V1beta1ProjectSpec(
                name = '',
                organization_ref = ome.models.v1beta1/cross_reference.v1beta1.CrossReference(
                    name = '', 
                    namespace = '', ),
        )
        """

    def testV1beta1ProjectSpec(self):
        """Test V1beta1ProjectSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
