# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_pod_config import V1beta1PodConfig


class TestV1beta1PodConfig(unittest.TestCase):
    """V1beta1PodConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1PodConfig:
        """Test V1beta1PodConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1PodConfig`
        """
        model = V1beta1PodConfig()
        if include_optional:
            return V1beta1PodConfig(
                cpu_limit = '',
                cpu_request = '',
                image = '',
                memory_limit = '',
                memory_request = ''
            )
        else:
            return V1beta1PodConfig(
                cpu_limit = '',
                cpu_request = '',
                image = '',
                memory_limit = '',
                memory_request = '',
        )
        """

    def testV1beta1PodConfig(self):
        """Test V1beta1PodConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
