# coding: utf-8

"""
OME

Python SDK for OME

The version of the OpenAPI document: v0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ome.models.v1beta1_model_extension_spec import V1beta1ModelExtensionSpec


class TestV1beta1ModelExtensionSpec(unittest.TestCase):
    """V1beta1ModelExtensionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ModelExtensionSpec:
        """Test V1beta1ModelExtensionSpec
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V1beta1ModelExtensionSpec`
        """
        model = V1beta1ModelExtensionSpec()
        if include_optional:
            return V1beta1ModelExtensionSpec(
                compartment_id = '',
                disabled = True,
                display_name = '',
                vendor = '',
                version = ''
            )
        else:
            return V1beta1ModelExtensionSpec(
        )
        """

    def testV1beta1ModelExtensionSpec(self):
        """Test V1beta1ModelExtensionSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
