# apiVersion: v1
# kind: Namespace
# metadata:
#   name: deepseek-v4
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: deepseek-v4-flash
  namespace: deepseek-v4
spec:
  model:
    name: deepseek-v4-flash
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
