{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ome-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ome-prometheus.labels" . | nindent 4 }}
{{- end }}
