apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: ome
data:
  ingress: |-
    {
        "ingressGateway" : "knative-serving/knative-ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "omeIngressGateway" : "",
        "ingressDomain"  : "svc.cluster.local",
        "ingressClassName" : "istio",
        "additionalIngressDomains" : null,
        "domainTemplate": "{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "http",
        "disableIstioVirtualHost": false,
        "pathTemplate": "",
        "disableIngressCreation": true,
        "enableGatewayAPI": false
    }

  deploy: |-
    {
      "defaultDeploymentMode": "RawDeployment"
    }

  modelInit: |-
    {
        "image" : "ghcr.io/moirai-internal/ome-agent:v1.2.1",
        "memoryRequest": "320Gi",
        "memoryLimit": "320Gi",
        "cpuRequest": "15",
        "cpuLimit": "15",
        "compartmentId": "ocid1.compartment.oc1..aaaaaaaarncfmdarfvbvhfj2oknyuvvftcp4p6ra77xlswftk67kcffmm2xq",
        "authType" : "InstancePrincipal",
        "vaultId": "ocid1.vault.oc1.eu-frankfurt-1.ens4gnknaaec4.abtheljrqneswo524ce3ytfqv3wqdjz4yi2drovyjnuo5lghz2fr76a7l7lq",
        "region": "eu-frankfurt-1",
        "extraEnvVars": [
          {
            "name": "INSTANCE_TYPE_MAP",
            "value": "{\"BM.GPU.A10.4\":\"A10\",\"BM.GPU.A100-v2.8\":\"A100-80G\",\"BM.GPU4.8\":\"A100-40G\",\"BM.GPU.B4.8\":\"A100-40G\",\"BM.GPU.H100.8\":\"H100\",\"BM.GPU.H100-NC.8\":\"H100\",\"BM.GPU.H200.8\":\"H200\",\"BM.GPU.H200-NC.8\":\"H200\",\"BM.GPU.B200.8\":\"B200\",\"BM.GPU.B300.8\":\"B300\",\"p5.48xlarge\":\"H100\",\"Standard_ND96isr_H100_v5\":\"H100\",\"a3-highgpu-8g\":\"H100\",\"gd-8xh100ib-i128\":\"H100\",\"gd-8xh200ib-i128\":\"H200\",\"gd-8xl40-i128\":\"L40\",\"gpu-h100-sxm\":\"H100\",\"gpu-h200-sxm\":\"H200\",\"gpu-b200-sxm\":\"B200\",\"gpu-l40s\":\"L40S\"}"
          }
        ]
    }

  multinodeProber: |-
    {
      "image" : "ghcr.io/moirai-internal/multinode-prober:v1.2.1",
      "memoryRequest": "100Mi",
      "memoryLimit": "100Mi",
      "cpuRequest": "100m",
      "cpuLimit": "100m",
      "startupFailureThreshold": 150,
      "startupPeriodSeconds": 30,
      "startupTimeoutSeconds": 60,
      "startupInitialDelaySeconds": 200,
      "unavailableThresholdSeconds": 1800
    }

  kedaConfig: |-
    {
      "enableKeda" : true,
      "promServerAddress": "http://prometheus-operated.monitoring.svc.cluster.local:9090",
      "customPromQuery": "",
      "scalingThreshold": "10",
      "scalingOperator": "GreaterThanOrEqual"
    }
