apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: ome
data:
  _example: |-
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.
     
     # ====================================== INGRESS CONFIGURATION ======================================
     # Example
     ingress: |-
       {
           "ingressGateway" : "knative-serving/knative-ingress-gateway",
           "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
           "localGateway" : "knative-serving/knative-local-gateway",
           "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
           "ingressDomain"  : "example.com",
           "additionalIngressDomains": ["additional-example.com", "additional-example-1.com"],
           "ingressClassName" : "istio",
           "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
           "urlScheme": "http",
           "disableIstioVirtualHost": false,
           "disableIngressCreation": false
       }
     ingress: |-
       {
           # ingressGateway specifies the ingress gateway to serve external traffic.
           # The gateway should be specified in format <gateway namespace>/<gateway name>
           # NOTE: This configuration only applicable for serverless deployment with Istio configured as network layer.
           "ingressGateway" : "knative-serving/knative-ingress-gateway",
     
           # ingressService specifies the hostname of the ingress service.
           # NOTE: This configuration only applicable for serverless deployment with Istio configured as network layer.
           "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
     
           # localGateway specifies the gateway which handles the network traffic within the cluster.
           # NOTE: This configuration only applicable for serverless deployment with Istio configured as network layer.
           "localGateway" : "knative-serving/knative-local-gateway",
     
           # localGatewayService specifies the hostname of the local gateway service.
           # NOTE: This configuration only applicable for serverless deployment with Istio configured as network layer.
           "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
     
           # ingressDomain specifies the domain name which is used for creating the url.
           # If ingressDomain is empty then example.com is used as default domain.
           # NOTE: This configuration only applicable for raw deployment.
           "ingressDomain"  : "example.com",

           # additionalIngressDomains specifies the additional domain names which are used for creating the url.
           "additionalIngressDomains": ["additional-example.com", "additional-example-1.com"]

           # ingressClassName specifies the ingress controller to use for ingress traffic.
           # This is optional and if omitted the default ingress in the cluster is used.
           # https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class
           # NOTE: This configuration only applicable for raw deployment.
           "ingressClassName" : "istio",
     
           # domainTemplate specifies the template for generating domain/url for each inference service by combining variable from:
           # Name of the inference service  ( {{ .Name}} )
           # Namespace of the inference service ( {{ .Namespace }} )
           # Annotation of the inference service ( {{ .Annotations.key }} )
           # Label of the inference service ( {{ .Labels.key }} )
           # IngressDomain ( {{ .IngressDomain }} )
           # If domain template is empty the default template {{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }} is used.
           # NOTE: This configuration only applicable for raw deployment.
           "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
     
           # urlScheme specifies the url scheme to use for inference service and inference graph.
           # If urlScheme is empty then by default http is used.
           "urlScheme": "http",
     
           # disableIstioVirtualHost controls whether to use istio as network layer.
           # By default istio is used as the network layer. When DisableIstioVirtualHost is true, ome does not
           # create the top level virtual service thus Istio is no longer required for serverless mode.
           # By setting this field to true, user can use other networking layers supported by knative.
           # NOTE: This configuration is only applicable to serverless deployment.
           "disableIstioVirtualHost": false,

           # disableIngressCreation controls whether to disable ingress creation for raw deployment mode.
           "disableIngressCreation": false,
     
           # pathTemplate specifies the template for generating path based url for each inference service.
           # The following variables can be used in the template for generating url.
           # Name of the inference service  ( {{ .Name}} )
           # Namespace of the inference service ( {{ .Namespace }} )
           # For more info https://bitbucket.oci.oraclecorp.com/gen/ome/issues/2257.
           # NOTE: This configuration only applicable to serverless deployment.
           "pathTemplate": "/serving/{{ .Namespace }}/{{ .Name }}"
       }
     
     # ====================================== LOGGER CONFIGURATION ======================================
     # Example
     logger: |-
       {
           "image" : "ome/agent:latest",
           "memoryRequest": "100Mi",
           "memoryLimit": "1Gi",
           "cpuRequest": "100m",
           "cpuLimit": "1",
           "defaultUrl": "http://default-broker"
       }
     logger: |-
       {
           # image contains the default logger image uri.
           "image" : "ome/agent:latest",
       
           # memoryRequest is the requests.memory to set for the logger container.
           "memoryRequest": "100Mi",
           
           # memoryLimit is the limits.memory to set for the logger container.
           "memoryLimit": "1Gi",
           
           # cpuRequest is the requests.cpu to set for the logger container.
           "cpuRequest": "100m",
           
           # cpuLimit is the limits.cpu to set for the logger container.
           "cpuLimit": "1",
           
           # defaultUrl specifies the default logger url. If logger is not specified in the resource this url is used.
           "defaultUrl": "http://default-broker"
       }
     
     # ====================================== AGENT CONFIGURATION ======================================
     # Example
     agent: |-
       {
           "image" : "ome/agent:latest",
           "memoryRequest": "100Mi",
           "memoryLimit": "1Gi",
           "cpuRequest": "100m",
           "cpuLimit": "1"
       }
     agent: |-
       {
           # image contains the default agent image uri.
           "image" : "ome/agent:latest",
       
           # memoryRequest is the requests.memory to set for the agent container.
           "memoryRequest": "100Mi",
       
           # memoryLimit is the limits.memory to set for the agent container.
           "memoryLimit": "1Gi",
           
           # cpuRequest is the requests.cpu to set for the agent container.
           "cpuRequest": "100m",
           
           # cpuLimit is the limits.cpu to set for the agent container.
           "cpuLimit": "1"
       }
     
     # ====================================== DEPLOYMENT CONFIGURATION ======================================
     # Example
     deploy: |-
       {
         "defaultDeploymentMode": "Serverless"
       }
     deploy: |-
       {
         # defaultDeploymentMode specifies the default deployment mode of the OME. The supported values are
         # Serverless and RawDeployment. Users can override the deployment mode at service level
         # by adding the annotation ome.oracle.com/deploymentMode.
         "defaultDeploymentMode": "Serverless"
       }
     
     # ====================================== METRICS CONFIGURATION ======================================
     # Example
     metricsAggregator: |-
       {
         "enableMetricAggregation": "false",
         "enablePrometheusScraping" : "false"
       }
     # For more info see https://bitbucket.oci.oraclecorp.com/gen/ome/blob/master/qpext/README.md
     metricsAggregator: |-
       {
         # enableMetricAggregation configures metric aggregation annotation. This adds the annotation ome.oracle.com/enable-metric-aggregation to every
         # service with the specified boolean value. If true enables metric aggregation in queue-proxy by setting env vars in the queue proxy container
         # to configure scraping ports.
         "enableMetricAggregation": "false",
         
         # enablePrometheusScraping configures metric aggregation annotation. This adds the annotation ome.oracle.com/enable-metric-aggregation to every
         # service with the specified boolean value. If true, prometheus annotations are added to the pod. If ome.oracle.com/enable-metric-aggregation is false,
         # the prometheus port is set with the default prometheus scraping port 9090, otherwise the prometheus port annotation is set with the metric aggregation port.
         "enablePrometheusScraping" : "false"
       }

  ingress: |-
    {
        "ingressGateway" : "knative-serving/knative-ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "knative-serving/knative-local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "ingressDomain"  : "example.com",
        "ingressClassName" : "istio",
        "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "http",
        "disableIstioVirtualHost": false,
        "disableIngressCreation": false
    }

  logger: |-
    {
        "image" : "ome/agent:latest",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1",
        "defaultUrl": "http://default-broker"
    }

  agent: |-
    {
        "image" : "ome/agent:latest",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }


  deploy: |-
    {
      "defaultDeploymentMode": "Serverless"
    }

  metricsAggregator: |-
    {
      "enableMetricAggregation": "false",
      "enablePrometheusScraping" : "false"
    }
