{{- if index .Values "cohere-rerank-v4-0-fast" "enabled" -}}
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: rerank-v4-0-fast
  labels:
    genai-managed-base-model-v1beta1: "true"
    genai-model-deprecated-date: "{{ index .Values "cohere-rerank-v4-0-fast" "timeDeprecated" }}"
    genai-model-on-demand-retired-date: "{{ index .Values "cohere-rerank-v4-0-fast" "timeOnDemandRetired" }}"
    genai-model-dedicated-retired-date: "{{ index .Values "cohere-rerank-v4-0-fast" "timeDedicatedRetired" }}"
  annotations:
    models.ome.io/runtime: "cohere-rerank-v4-0-fast"
    models.ome.io/category: "SMALL"
    models.ome.io/experimental: "{{ index .Values "cohere-rerank-v4-0-fast" "isExperimental" }}"
    models.ome.io/internal: "{{ index .Values "cohere-rerank-v4-0-fast" "isInternal" }}"
    models.ome.io/lifecycle-phase: "{{ index .Values "cohere-rerank-v4-0-fast" "lifecyclePhase" }}"
    ome.io/base-model-decryption-key-name: "rerank"
    ome.io/base-model-decryption-secret-name: "rerank-dek"
spec:
  compartmentID: {{ .Values.compartmentID }}
  disabled: false
  displayName: cohere.rerank-v4.0-fast
  storage:
    storageUri: "oci://n/{{ .Values.osnamespace }}/b/{{ index .Values "cohere-rerank-v4-0-fast" "osBucket" }}/o/{{ index .Values "cohere-rerank-v4-0-fast" "vendor" }}/{{ index .Values "cohere-rerank-v4-0-fast" "osPrefixOverride" }}"
    path: "/mnt/data/models/{{ index .Values "cohere-rerank-v4-0-fast" "vendor" }}/{{ index .Values "cohere-rerank-v4-0-fast" "osPrefixOverride" }}"
  vendor: {{ index .Values "cohere-rerank-v4-0-fast" "vendor" }}
  version: "4.0"
  modelFormat:
    name: onnx
    version: '1'
  modelFramework:
    name: onnxruntime
    version: '1'
  modelArchitecture: CohereForCausalLM
  modelParameterSize: 400M
  modelCapabilities:
    - "TEXT_RERANK"
  maxTokens: 4096
  additionalMetadata:
    dacShapeConfigs: |-
      compatibleDACShapes:
        - name: RERANK_COHERE
          quotaUnit: 1
          default: true
    internalName: "rerank-v4-0-fast"
    type: "Serving"
{{- end }}