---
apiVersion: v1
kind: Namespace
metadata:
  name: mistralai
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: devstral-2-123b-instruct-2512
  namespace: mistralai
spec:
  model:
    name: devstral-2-123b-instruct-2512
  engine:
    minReplicas: 1
    maxReplicas: 1
