// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/serving/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrainingRuntimes implements TrainingRuntimeInterface
type FakeTrainingRuntimes struct {
	Fake *FakeOmeV1beta1
	ns   string
}

var trainingruntimesResource = v1beta1.SchemeGroupVersion.WithResource("trainingruntimes")

var trainingruntimesKind = v1beta1.SchemeGroupVersion.WithKind("TrainingRuntime")

// Get takes name of the trainingRuntime, and returns the corresponding trainingRuntime object, and an error if there is any.
func (c *FakeTrainingRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.TrainingRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trainingruntimesResource, c.ns, name), &v1beta1.TrainingRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TrainingRuntime), err
}

// List takes label and field selectors, and returns the list of TrainingRuntimes that match those selectors.
func (c *FakeTrainingRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.TrainingRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trainingruntimesResource, trainingruntimesKind, c.ns, opts), &v1beta1.TrainingRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.TrainingRuntimeList{ListMeta: obj.(*v1beta1.TrainingRuntimeList).ListMeta}
	for _, item := range obj.(*v1beta1.TrainingRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trainingRuntimes.
func (c *FakeTrainingRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trainingruntimesResource, c.ns, opts))

}

// Create takes the representation of a trainingRuntime and creates it.  Returns the server's representation of the trainingRuntime, and an error, if there is any.
func (c *FakeTrainingRuntimes) Create(ctx context.Context, trainingRuntime *v1beta1.TrainingRuntime, opts v1.CreateOptions) (result *v1beta1.TrainingRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trainingruntimesResource, c.ns, trainingRuntime), &v1beta1.TrainingRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TrainingRuntime), err
}

// Update takes the representation of a trainingRuntime and updates it. Returns the server's representation of the trainingRuntime, and an error, if there is any.
func (c *FakeTrainingRuntimes) Update(ctx context.Context, trainingRuntime *v1beta1.TrainingRuntime, opts v1.UpdateOptions) (result *v1beta1.TrainingRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trainingruntimesResource, c.ns, trainingRuntime), &v1beta1.TrainingRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TrainingRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrainingRuntimes) UpdateStatus(ctx context.Context, trainingRuntime *v1beta1.TrainingRuntime, opts v1.UpdateOptions) (*v1beta1.TrainingRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trainingruntimesResource, "status", c.ns, trainingRuntime), &v1beta1.TrainingRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TrainingRuntime), err
}

// Delete takes name of the trainingRuntime and deletes it. Returns an error if one occurs.
func (c *FakeTrainingRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(trainingruntimesResource, c.ns, name, opts), &v1beta1.TrainingRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrainingRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trainingruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.TrainingRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched trainingRuntime.
func (c *FakeTrainingRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.TrainingRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trainingruntimesResource, c.ns, name, pt, data, subresources...), &v1beta1.TrainingRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TrainingRuntime), err
}
