llama-3-1-70b-instruct:
  enabled: true
  minReplicas: 1
  maxReplicas: 1

llama-3-1-405b-instruct-fp8:
  enabled: false
  minReplicas: 1
  maxReplicas: 1

llama-3-1-405b-instruct-fp8-pp:
  enabled: true
  minReplicas: 2
  maxReplicas: 2

llama-3-1-405b-instruct-fp8-rdma:
  enabled: false
  minReplicas: 2
  maxReplicas: 2

phi-3-mini-128k-instruct:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
