vllm:
  port: 8080
  serveModelName: vllm-model
  commonImage:
    repository: &defaultVLLMImage fra.ocir.io/idqj093njucb/official-vllm-openai
    tag: &defaultVLLMImageTag 0.5.3.post1.7f8d612d-log

commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
  linkerd.io/inject: "enabled"

commonLabels:
  logging-forward: enabled

commonTolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"


llama_3_1_70b_instruct:
  enabled: false
  annotations: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

llama_3_1_405b_instruct:
  enabled: false
  enableRDMA: false
  annotations: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  # The number of replicas to start with must be 2 or more, as the model is too large to fit in a single GPU node
  minReplicas: 1
  maxReplicas: 1
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

phi_3_mini_128k_instruct:
  enabled: false
  annotations: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  volumes: [ ]
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

e5_mistral_7b_instruct:
  enabled: false
  annotations: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  volumes: [ ]
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag
