vllm:
  port: 8080
  serveModelName: vllm-model
  commonImage:
    repository: &defaultVLLMImage fra.ocir.io/idqj093njucb/official-vllm-openai
    tag: &defaultVLLMImageTag 0.5.3.post1.7f8d612d-log
  llama3_2_image:
    tag: v0.6.2.e019c49f

commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
  linkerd.io/inject: "enabled"
  chainsaw.k8s-integration.oracle.com/compartmentId: "ocid1.compartment.oc1..aaaaaaaathgntpo75bdehisnl6wkxfc4slkd6rpheafbt5a6ekm2ri4bmeva" # hardcode to dev tenancy compartment id
  chainsaw.k8s-integration.oracle.com/inject: "enabled"
  chainsaw.k8s-integration.oracle.com/logPath: "vllm"
  chainsaw.k8s-integration.oracle.com/namespace: "vllm"

commonLabels:
  logging-forward: enabled

commonTolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"

llama_3_1_70b_instruct:
  enabled: false
  annotations:
    ome.io/autoscalerClass: "keda"
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

llama_3_1_405b_instruct:
  enabled: false
  enableRDMA: false
  annotations:
    config.linkerd.io/skip-inbound-ports: "1-8079,8081-65535"
    config.linkerd.io/skip-outbound-ports: "1-8079,8081-65535"
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  # The number of replicas to start with must be 2 or more, as the model is too large to fit in a single GPU node
  minReplicas: 1
  maxReplicas: 1
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

phi_3_mini_128k_instruct:
  enabled: false
  annotations: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  volumes: [ ]
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

e5_mistral_7b_instruct:
  enabled: false
  annotations: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  volumes: [ ]
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

llama_3_2_90b_vision_instruct:
  enabled: false
  annotations: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

llama_3_2_90b_vision_fp8_dynamic:
  enabled: false
  annotations: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

llama_3_2_11b_vision_instruct:
  enabled: false
  annotations: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  volumes: []
  minReplicas: 1
  maxReplicas: 1
  scaleMetric: {}
  image:
    repository: *defaultVLLMImage
    tag: *defaultVLLMImageTag

deberta_v3_base_prompt_injection_v2:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  image:
    repository: fra.ocir.io/idqj093njucb/genai-prompt-injection-protection
    tag: v0.1-24-release