// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
)

// AutoscalerPolicyLister helps list AutoscalerPolicies.
// All objects returned here must be treated as read-only.
type AutoscalerPolicyLister interface {
	// List lists all AutoscalerPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.AutoscalerPolicy, err error)
	// AutoscalerPolicies returns an object that can list and get AutoscalerPolicies.
	AutoscalerPolicies(namespace string) AutoscalerPolicyNamespaceLister
	AutoscalerPolicyListerExpansion
}

// autoscalerPolicyLister implements the AutoscalerPolicyLister interface.
type autoscalerPolicyLister struct {
	listers.ResourceIndexer[*omev1beta1.AutoscalerPolicy]
}

// NewAutoscalerPolicyLister returns a new AutoscalerPolicyLister.
func NewAutoscalerPolicyLister(indexer cache.Indexer) AutoscalerPolicyLister {
	return &autoscalerPolicyLister{listers.New[*omev1beta1.AutoscalerPolicy](indexer, omev1beta1.Resource("autoscalerpolicy"))}
}

// AutoscalerPolicies returns an object that can list and get AutoscalerPolicies.
func (s *autoscalerPolicyLister) AutoscalerPolicies(namespace string) AutoscalerPolicyNamespaceLister {
	return autoscalerPolicyNamespaceLister{listers.NewNamespaced[*omev1beta1.AutoscalerPolicy](s.ResourceIndexer, namespace)}
}

// AutoscalerPolicyNamespaceLister helps list and get AutoscalerPolicies.
// All objects returned here must be treated as read-only.
type AutoscalerPolicyNamespaceLister interface {
	// List lists all AutoscalerPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.AutoscalerPolicy, err error)
	// Get retrieves the AutoscalerPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*omev1beta1.AutoscalerPolicy, error)
	AutoscalerPolicyNamespaceListerExpansion
}

// autoscalerPolicyNamespaceLister implements the AutoscalerPolicyNamespaceLister
// interface.
type autoscalerPolicyNamespaceLister struct {
	listers.ResourceIndexer[*omev1beta1.AutoscalerPolicy]
}
