// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BaseModelListerExpansion allows custom methods to be added to
// BaseModelLister.
type BaseModelListerExpansion interface{}

// BaseModelNamespaceListerExpansion allows custom methods to be added to
// BaseModelNamespaceLister.
type BaseModelNamespaceListerExpansion interface{}

// BenchmarkJobListerExpansion allows custom methods to be added to
// BenchmarkJobLister.
type BenchmarkJobListerExpansion interface{}

// BenchmarkJobNamespaceListerExpansion allows custom methods to be added to
// BenchmarkJobNamespaceLister.
type BenchmarkJobNamespaceListerExpansion interface{}

// CapacityReservationListerExpansion allows custom methods to be added to
// CapacityReservationLister.
type CapacityReservationListerExpansion interface{}

// CapacityReservationNamespaceListerExpansion allows custom methods to be added to
// CapacityReservationNamespaceLister.
type CapacityReservationNamespaceListerExpansion interface{}

// ClusterBaseModelListerExpansion allows custom methods to be added to
// ClusterBaseModelLister.
type ClusterBaseModelListerExpansion interface{}

// ClusterCapacityReservationListerExpansion allows custom methods to be added to
// ClusterCapacityReservationLister.
type ClusterCapacityReservationListerExpansion interface{}

// ClusterServingRuntimeListerExpansion allows custom methods to be added to
// ClusterServingRuntimeLister.
type ClusterServingRuntimeListerExpansion interface{}

// ClusterTrainingRuntimeListerExpansion allows custom methods to be added to
// ClusterTrainingRuntimeLister.
type ClusterTrainingRuntimeListerExpansion interface{}

// DedicatedAIClusterListerExpansion allows custom methods to be added to
// DedicatedAIClusterLister.
type DedicatedAIClusterListerExpansion interface{}

// DedicatedAIClusterProfileListerExpansion allows custom methods to be added to
// DedicatedAIClusterProfileLister.
type DedicatedAIClusterProfileListerExpansion interface{}

// FineTunedWeightListerExpansion allows custom methods to be added to
// FineTunedWeightLister.
type FineTunedWeightListerExpansion interface{}

// FineTunedWeightNamespaceListerExpansion allows custom methods to be added to
// FineTunedWeightNamespaceLister.
type FineTunedWeightNamespaceListerExpansion interface{}

// InferenceServiceListerExpansion allows custom methods to be added to
// InferenceServiceLister.
type InferenceServiceListerExpansion interface{}

// InferenceServiceNamespaceListerExpansion allows custom methods to be added to
// InferenceServiceNamespaceLister.
type InferenceServiceNamespaceListerExpansion interface{}

// OrganizationListerExpansion allows custom methods to be added to
// OrganizationLister.
type OrganizationListerExpansion interface{}

// ProjectListerExpansion allows custom methods to be added to
// ProjectLister.
type ProjectListerExpansion interface{}

// RateLimitListerExpansion allows custom methods to be added to
// RateLimitLister.
type RateLimitListerExpansion interface{}

// ServiceAccountListerExpansion allows custom methods to be added to
// ServiceAccountLister.
type ServiceAccountListerExpansion interface{}

// ServingRuntimeListerExpansion allows custom methods to be added to
// ServingRuntimeLister.
type ServingRuntimeListerExpansion interface{}

// ServingRuntimeNamespaceListerExpansion allows custom methods to be added to
// ServingRuntimeNamespaceLister.
type ServingRuntimeNamespaceListerExpansion interface{}

// TrainingJobListerExpansion allows custom methods to be added to
// TrainingJobLister.
type TrainingJobListerExpansion interface{}

// TrainingJobNamespaceListerExpansion allows custom methods to be added to
// TrainingJobNamespaceLister.
type TrainingJobNamespaceListerExpansion interface{}

// TrainingRuntimeListerExpansion allows custom methods to be added to
// TrainingRuntimeLister.
type TrainingRuntimeListerExpansion interface{}

// TrainingRuntimeNamespaceListerExpansion allows custom methods to be added to
// TrainingRuntimeNamespaceLister.
type TrainingRuntimeNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}
