// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
)

// InferenceReplicaLister helps list InferenceReplicas.
// All objects returned here must be treated as read-only.
type InferenceReplicaLister interface {
	// List lists all InferenceReplicas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.InferenceReplica, err error)
	// InferenceReplicas returns an object that can list and get InferenceReplicas.
	InferenceReplicas(namespace string) InferenceReplicaNamespaceLister
	InferenceReplicaListerExpansion
}

// inferenceReplicaLister implements the InferenceReplicaLister interface.
type inferenceReplicaLister struct {
	listers.ResourceIndexer[*omev1beta1.InferenceReplica]
}

// NewInferenceReplicaLister returns a new InferenceReplicaLister.
func NewInferenceReplicaLister(indexer cache.Indexer) InferenceReplicaLister {
	return &inferenceReplicaLister{listers.New[*omev1beta1.InferenceReplica](indexer, omev1beta1.Resource("inferencereplica"))}
}

// InferenceReplicas returns an object that can list and get InferenceReplicas.
func (s *inferenceReplicaLister) InferenceReplicas(namespace string) InferenceReplicaNamespaceLister {
	return inferenceReplicaNamespaceLister{listers.NewNamespaced[*omev1beta1.InferenceReplica](s.ResourceIndexer, namespace)}
}

// InferenceReplicaNamespaceLister helps list and get InferenceReplicas.
// All objects returned here must be treated as read-only.
type InferenceReplicaNamespaceLister interface {
	// List lists all InferenceReplicas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.InferenceReplica, err error)
	// Get retrieves the InferenceReplica from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*omev1beta1.InferenceReplica, error)
	InferenceReplicaNamespaceListerExpansion
}

// inferenceReplicaNamespaceLister implements the InferenceReplicaNamespaceLister
// interface.
type inferenceReplicaNamespaceLister struct {
	listers.ResourceIndexer[*omev1beta1.InferenceReplica]
}
