// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OciCacheLister helps list OciCaches.
// All objects returned here must be treated as read-only.
type OciCacheLister interface {
	// List lists all OciCaches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.OciCache, err error)
	// OciCaches returns an object that can list and get OciCaches.
	OciCaches(namespace string) OciCacheNamespaceLister
	OciCacheListerExpansion
}

// ociCacheLister implements the OciCacheLister interface.
type ociCacheLister struct {
	listers.ResourceIndexer[*omev1beta1.OciCache]
}

// NewOciCacheLister returns a new OciCacheLister.
func NewOciCacheLister(indexer cache.Indexer) OciCacheLister {
	return &ociCacheLister{listers.New[*omev1beta1.OciCache](indexer, omev1beta1.Resource("ocicache"))}
}

// OciCaches returns an object that can list and get OciCaches.
func (s *ociCacheLister) OciCaches(namespace string) OciCacheNamespaceLister {
	return ociCacheNamespaceLister{listers.NewNamespaced[*omev1beta1.OciCache](s.ResourceIndexer, namespace)}
}

// OciCacheNamespaceLister helps list and get OciCaches.
// All objects returned here must be treated as read-only.
type OciCacheNamespaceLister interface {
	// List lists all OciCaches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*omev1beta1.OciCache, err error)
	// Get retrieves the OciCache from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*omev1beta1.OciCache, error)
	OciCacheNamespaceListerExpansion
}

// ociCacheNamespaceLister implements the OciCacheNamespaceLister
// interface.
type ociCacheNamespaceLister struct {
	listers.ResourceIndexer[*omev1beta1.OciCache]
}
