// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// OciPostgresClusterLister helps list OciPostgresClusters.
// All objects returned here must be treated as read-only.
type OciPostgresClusterLister interface {
	// List lists all OciPostgresClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.OciPostgresCluster, err error)
	// OciPostgresClusters returns an object that can list and get OciPostgresClusters.
	OciPostgresClusters(namespace string) OciPostgresClusterNamespaceLister
	OciPostgresClusterListerExpansion
}

// ociPostgresClusterLister implements the OciPostgresClusterLister interface.
type ociPostgresClusterLister struct {
	listers.ResourceIndexer[*v1beta1.OciPostgresCluster]
}

// NewOciPostgresClusterLister returns a new OciPostgresClusterLister.
func NewOciPostgresClusterLister(indexer cache.Indexer) OciPostgresClusterLister {
	return &ociPostgresClusterLister{listers.New[*v1beta1.OciPostgresCluster](indexer, v1beta1.Resource("ocipostgrescluster"))}
}

// OciPostgresClusters returns an object that can list and get OciPostgresClusters.
func (s *ociPostgresClusterLister) OciPostgresClusters(namespace string) OciPostgresClusterNamespaceLister {
	return ociPostgresClusterNamespaceLister{listers.NewNamespaced[*v1beta1.OciPostgresCluster](s.ResourceIndexer, namespace)}
}

// OciPostgresClusterNamespaceLister helps list and get OciPostgresClusters.
// All objects returned here must be treated as read-only.
type OciPostgresClusterNamespaceLister interface {
	// List lists all OciPostgresClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.OciPostgresCluster, err error)
	// Get retrieves the OciPostgresCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.OciPostgresCluster, error)
	OciPostgresClusterNamespaceListerExpansion
}

// ociPostgresClusterNamespaceLister implements the OciPostgresClusterNamespaceLister
// interface.
type ociPostgresClusterNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.OciPostgresCluster]
}
