// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// OciRedisClusterLister helps list OciRedisClusters.
// All objects returned here must be treated as read-only.
type OciRedisClusterLister interface {
	// List lists all OciRedisClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.OciRedisCluster, err error)
	// OciRedisClusters returns an object that can list and get OciRedisClusters.
	OciRedisClusters(namespace string) OciRedisClusterNamespaceLister
	OciRedisClusterListerExpansion
}

// ociRedisClusterLister implements the OciRedisClusterLister interface.
type ociRedisClusterLister struct {
	listers.ResourceIndexer[*v1beta1.OciRedisCluster]
}

// NewOciRedisClusterLister returns a new OciRedisClusterLister.
func NewOciRedisClusterLister(indexer cache.Indexer) OciRedisClusterLister {
	return &ociRedisClusterLister{listers.New[*v1beta1.OciRedisCluster](indexer, v1beta1.Resource("ocirediscluster"))}
}

// OciRedisClusters returns an object that can list and get OciRedisClusters.
func (s *ociRedisClusterLister) OciRedisClusters(namespace string) OciRedisClusterNamespaceLister {
	return ociRedisClusterNamespaceLister{listers.NewNamespaced[*v1beta1.OciRedisCluster](s.ResourceIndexer, namespace)}
}

// OciRedisClusterNamespaceLister helps list and get OciRedisClusters.
// All objects returned here must be treated as read-only.
type OciRedisClusterNamespaceLister interface {
	// List lists all OciRedisClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.OciRedisCluster, err error)
	// Get retrieves the OciRedisCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.OciRedisCluster, error)
	OciRedisClusterNamespaceListerExpansion
}

// ociRedisClusterNamespaceLister implements the OciRedisClusterNamespaceLister
// interface.
type ociRedisClusterNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.OciRedisCluster]
}
