// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RateLimitLister helps list RateLimits.
// All objects returned here must be treated as read-only.
type RateLimitLister interface {
	// List lists all RateLimits in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.RateLimit, err error)
	// Get retrieves the RateLimit from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.RateLimit, error)
	RateLimitListerExpansion
}

// rateLimitLister implements the RateLimitLister interface.
type rateLimitLister struct {
	listers.ResourceIndexer[*v1beta1.RateLimit]
}

// NewRateLimitLister returns a new RateLimitLister.
func NewRateLimitLister(indexer cache.Indexer) RateLimitLister {
	return &rateLimitLister{listers.New[*v1beta1.RateLimit](indexer, v1beta1.Resource("ratelimit"))}
}
