apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: srt-glm-text-fp8-tp8
spec:
  disabled: false
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.54.0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: Glm4MoeForCausalLM
      quantization: fp8
      autoSelect: true
      priority: 1
    - modelFramework:
        name: transformers
        version: "4.52.3"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: Glm4MoeForCausalLM
      quantization: fp8
      autoSelect: true
      priority: 1
  protocolVersions:
    - openAI
  modelSizeRange:
    min: 350B
    max: 360B
  engineConfig:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
    labels:
      logging-forward: enabled
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
    runner:
      name: ome-container
      image: ghcr.io/lightseekorg/smg:1.3.2-sglang-v0.5.9
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      command:
        - python3
        - -m
        - sglang.launch_server
        - --host
        - "0.0.0.0"
        - --port
        - "8080"
        - --enable-metrics
        - --log-requests
        - --model-path
        - $(MODEL_PATH)
        - --tp-size
        - "8"
        - --mem-fraction-static
        - "0.8"
        - --trust-remote-code
        - --tool-call-parser
        - glm47
        - --reasoning-parser
        - glm45
        - --speculative-algorithm
        - EAGLE
        - --speculative-num-steps
        - "3"
        - --speculative-eagle-topk
        - "1"
        - --speculative-num-draft-tokens
        - "4"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 40
          memory: 640Gi
          nvidia.com/gpu: 8
        limits:
          cpu: 40
          memory: 640Gi
          nvidia.com/gpu: 8

      readinessProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 90
        timeoutSeconds: 20

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health_generate
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
