// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/gen/ome/pkg/apis/serving/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterBaseModelLister helps list ClusterBaseModels.
// All objects returned here must be treated as read-only.
type ClusterBaseModelLister interface {
	// List lists all ClusterBaseModels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ClusterBaseModel, err error)
	// ClusterBaseModels returns an object that can list and get ClusterBaseModels.
	ClusterBaseModels(namespace string) ClusterBaseModelNamespaceLister
	ClusterBaseModelListerExpansion
}

// clusterBaseModelLister implements the ClusterBaseModelLister interface.
type clusterBaseModelLister struct {
	indexer cache.Indexer
}

// NewClusterBaseModelLister returns a new ClusterBaseModelLister.
func NewClusterBaseModelLister(indexer cache.Indexer) ClusterBaseModelLister {
	return &clusterBaseModelLister{indexer: indexer}
}

// List lists all ClusterBaseModels in the indexer.
func (s *clusterBaseModelLister) List(selector labels.Selector) (ret []*v1beta1.ClusterBaseModel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ClusterBaseModel))
	})
	return ret, err
}

// ClusterBaseModels returns an object that can list and get ClusterBaseModels.
func (s *clusterBaseModelLister) ClusterBaseModels(namespace string) ClusterBaseModelNamespaceLister {
	return clusterBaseModelNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ClusterBaseModelNamespaceLister helps list and get ClusterBaseModels.
// All objects returned here must be treated as read-only.
type ClusterBaseModelNamespaceLister interface {
	// List lists all ClusterBaseModels in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.ClusterBaseModel, err error)
	// Get retrieves the ClusterBaseModel from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.ClusterBaseModel, error)
	ClusterBaseModelNamespaceListerExpansion
}

// clusterBaseModelNamespaceLister implements the ClusterBaseModelNamespaceLister
// interface.
type clusterBaseModelNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ClusterBaseModels in the indexer for a given namespace.
func (s clusterBaseModelNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.ClusterBaseModel, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.ClusterBaseModel))
	})
	return ret, err
}

// Get retrieves the ClusterBaseModel from the indexer for a given namespace and name.
func (s clusterBaseModelNamespaceLister) Get(name string) (*v1beta1.ClusterBaseModel, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("clusterbasemodel"), name)
	}
	return obj.(*v1beta1.ClusterBaseModel), nil
}
