// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "bitbucket.oci.oraclecorp.com/gen/ome/pkg/apis/serving/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DedicatedAIClusterLister helps list DedicatedAIClusters.
// All objects returned here must be treated as read-only.
type DedicatedAIClusterLister interface {
	// List lists all DedicatedAIClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.DedicatedAICluster, err error)
	// Get retrieves the DedicatedAICluster from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.DedicatedAICluster, error)
	DedicatedAIClusterListerExpansion
}

// dedicatedAIClusterLister implements the DedicatedAIClusterLister interface.
type dedicatedAIClusterLister struct {
	indexer cache.Indexer
}

// NewDedicatedAIClusterLister returns a new DedicatedAIClusterLister.
func NewDedicatedAIClusterLister(indexer cache.Indexer) DedicatedAIClusterLister {
	return &dedicatedAIClusterLister{indexer: indexer}
}

// List lists all DedicatedAIClusters in the indexer.
func (s *dedicatedAIClusterLister) List(selector labels.Selector) (ret []*v1beta1.DedicatedAICluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.DedicatedAICluster))
	})
	return ret, err
}

// Get retrieves the DedicatedAICluster from the index for a given name.
func (s *dedicatedAIClusterLister) Get(name string) (*v1beta1.DedicatedAICluster, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("dedicatedaicluster"), name)
	}
	return obj.(*v1beta1.DedicatedAICluster), nil
}
