apiVersion: ome.io/v1beta1
kind: BenchmarkJob
metadata:
  name: e5-mistral-7b-instruct-benchmark
  namespace: e5-mistral-7b-instruct
spec:
  podOverride:
    image: "phx.ocir.io/idqj093njucb/genai-bench:0.1.120"
  endpoint:
    inferenceService:
      name: e5-mistral-7b-instruct
      namespace: e5-mistral-7b-instruct
  task: text-to-embeddings
  trafficScenarios:
    - "E(128)"
    - "E(512)"
    - "E(1024)"
    - "E(2048)"
    - "E(4096)"
    - "E(32000)"
  maxTimePerIteration: 15
  maxRequestsPerIteration: 15000
  serviceMetadata:
    engine: "SGLang"
    version: "v0.4.0.post1"
    gpuType: "H100"
    gpuCount: 2
  outputLocation:
    storageUri: "oci://n/idqj093njucb/b/test-bucket/o/e5-mistral-7b-instruct-benchmark"
    parameters:
      auth: "instance_principal"
      region: "us-chicago-1"