apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: vllm-minimax-m2-5-fp8-tp8
spec:
  disabled: false
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.46.1"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      modelArchitecture: MiniMaxM2ForCausalLM
      quantization: fp8
      autoSelect: true
      priority: 1
  protocolVersions:
    - openAI
  modelSizeRange:
    min: 220B
    max: 235B
  engineConfig:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
    labels:
      logging-forward: enabled
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
    runner:
      name: ome-container
      image: ghcr.io/lightseekorg/smg:1.3.2-vllm-v0.17.0
      env:
        - name: SAFETENSORS_FAST_GPU
          value: "1"
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --host
        - "0.0.0.0"
        - --port
        - "8080"
        - --model
        - $(MODEL_PATH)
        - --tensor-parallel-size
        - "8"
        - --gpu-memory-utilization
        - "0.9"
        - --trust-remote-code
        - --enable_expert_parallel
        - --enable-auto-tool-choice
        - --tool-call-parser
        - minimax_m2
        - --reasoning-parser
        - minimax_m2_append_think
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 40
          memory: 640Gi
          nvidia.com/gpu: 8
        limits:
          cpu: 40
          memory: 640Gi
          nvidia.com/gpu: 8

      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 90
        timeoutSeconds: 20

      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 150
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
