apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen2-vl-7b-instruct
spec:
  modelCapabilities:
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen2-vl-7b-instruct
  modelArchitecture: Qwen2VLForConditionalGeneration
  disabled: false
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.41.2"
  modelParameterSize: 7B
  storage:
    storageUri: hf://Qwen/Qwen2-VL-7B-Instruct
    path: /raid/models/Qwen/Qwen2-VL-7B-Instruct
