apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: qwen3-6-35b-a3b
spec:
  modelCapabilities:
    - TEXT_TO_TEXT
    - IMAGE_TEXT_TO_TEXT
    - VIDEO_TEXT_TO_TEXT
  vendor: Qwen
  displayName: qwen.qwen3.6-35b-a3b
  modelArchitecture: Qwen3_5MoeForConditionalGeneration
  disabled: false
  version: "1.0.0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelFramework:
    name: transformers
    version: "4.57.1"
  modelParameterSize: 35B
  storage:
    storageUri: hf://Qwen/Qwen3.6-35B-A3B
    path: /raid/models/Qwen/Qwen3.6-35B-A3B
