// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	scheme "sigs.k8s.io/ome/pkg/client/clientset/versioned/scheme"
)

// AcceleratorClassesGetter has a method to return a AcceleratorClassInterface.
// A group's client should implement this interface.
type AcceleratorClassesGetter interface {
	AcceleratorClasses() AcceleratorClassInterface
}

// AcceleratorClassInterface has methods to work with AcceleratorClass resources.
type AcceleratorClassInterface interface {
	Create(ctx context.Context, acceleratorClass *omev1beta1.AcceleratorClass, opts v1.CreateOptions) (*omev1beta1.AcceleratorClass, error)
	Update(ctx context.Context, acceleratorClass *omev1beta1.AcceleratorClass, opts v1.UpdateOptions) (*omev1beta1.AcceleratorClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, acceleratorClass *omev1beta1.AcceleratorClass, opts v1.UpdateOptions) (*omev1beta1.AcceleratorClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*omev1beta1.AcceleratorClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*omev1beta1.AcceleratorClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *omev1beta1.AcceleratorClass, err error)
	AcceleratorClassExpansion
}

// acceleratorClasses implements AcceleratorClassInterface
type acceleratorClasses struct {
	*gentype.ClientWithList[*omev1beta1.AcceleratorClass, *omev1beta1.AcceleratorClassList]
}

// newAcceleratorClasses returns a AcceleratorClasses
func newAcceleratorClasses(c *OmeV1beta1Client) *acceleratorClasses {
	return &acceleratorClasses{
		gentype.NewClientWithList[*omev1beta1.AcceleratorClass, *omev1beta1.AcceleratorClassList](
			"acceleratorclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *omev1beta1.AcceleratorClass { return &omev1beta1.AcceleratorClass{} },
			func() *omev1beta1.AcceleratorClassList { return &omev1beta1.AcceleratorClassList{} },
		),
	}
}
