// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	omev1beta1 "sigs.k8s.io/ome/pkg/apis/ome/v1beta1"
	scheme "sigs.k8s.io/ome/pkg/client/clientset/versioned/scheme"
)

// AcceleratorQuotasGetter has a method to return a AcceleratorQuotaInterface.
// A group's client should implement this interface.
type AcceleratorQuotasGetter interface {
	AcceleratorQuotas() AcceleratorQuotaInterface
}

// AcceleratorQuotaInterface has methods to work with AcceleratorQuota resources.
type AcceleratorQuotaInterface interface {
	Create(ctx context.Context, acceleratorQuota *omev1beta1.AcceleratorQuota, opts v1.CreateOptions) (*omev1beta1.AcceleratorQuota, error)
	Update(ctx context.Context, acceleratorQuota *omev1beta1.AcceleratorQuota, opts v1.UpdateOptions) (*omev1beta1.AcceleratorQuota, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, acceleratorQuota *omev1beta1.AcceleratorQuota, opts v1.UpdateOptions) (*omev1beta1.AcceleratorQuota, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*omev1beta1.AcceleratorQuota, error)
	List(ctx context.Context, opts v1.ListOptions) (*omev1beta1.AcceleratorQuotaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *omev1beta1.AcceleratorQuota, err error)
	AcceleratorQuotaExpansion
}

// acceleratorQuotas implements AcceleratorQuotaInterface
type acceleratorQuotas struct {
	*gentype.ClientWithList[*omev1beta1.AcceleratorQuota, *omev1beta1.AcceleratorQuotaList]
}

// newAcceleratorQuotas returns a AcceleratorQuotas
func newAcceleratorQuotas(c *OmeV1beta1Client) *acceleratorQuotas {
	return &acceleratorQuotas{
		gentype.NewClientWithList[*omev1beta1.AcceleratorQuota, *omev1beta1.AcceleratorQuotaList](
			"acceleratorquotas",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *omev1beta1.AcceleratorQuota { return &omev1beta1.AcceleratorQuota{} },
			func() *omev1beta1.AcceleratorQuotaList { return &omev1beta1.AcceleratorQuotaList{} },
		),
	}
}
