// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	scheme "github.com/sgl-project/sgl-ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CapacityReservationsGetter has a method to return a CapacityReservationInterface.
// A group's client should implement this interface.
type CapacityReservationsGetter interface {
	CapacityReservations(namespace string) CapacityReservationInterface
}

// CapacityReservationInterface has methods to work with CapacityReservation resources.
type CapacityReservationInterface interface {
	Create(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.CreateOptions) (*v1beta1.CapacityReservation, error)
	Update(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.UpdateOptions) (*v1beta1.CapacityReservation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, capacityReservation *v1beta1.CapacityReservation, opts v1.UpdateOptions) (*v1beta1.CapacityReservation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.CapacityReservation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.CapacityReservationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.CapacityReservation, err error)
	CapacityReservationExpansion
}

// capacityReservations implements CapacityReservationInterface
type capacityReservations struct {
	*gentype.ClientWithList[*v1beta1.CapacityReservation, *v1beta1.CapacityReservationList]
}

// newCapacityReservations returns a CapacityReservations
func newCapacityReservations(c *OmeV1beta1Client, namespace string) *capacityReservations {
	return &capacityReservations{
		gentype.NewClientWithList[*v1beta1.CapacityReservation, *v1beta1.CapacityReservationList](
			"capacityreservations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.CapacityReservation { return &v1beta1.CapacityReservation{} },
			func() *v1beta1.CapacityReservationList { return &v1beta1.CapacityReservationList{} }),
	}
}
