// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	scheme "github.com/sgl-project/sgl-ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterServingRuntimesGetter has a method to return a ClusterServingRuntimeInterface.
// A group's client should implement this interface.
type ClusterServingRuntimesGetter interface {
	ClusterServingRuntimes() ClusterServingRuntimeInterface
}

// ClusterServingRuntimeInterface has methods to work with ClusterServingRuntime resources.
type ClusterServingRuntimeInterface interface {
	Create(ctx context.Context, clusterServingRuntime *v1beta1.ClusterServingRuntime, opts v1.CreateOptions) (*v1beta1.ClusterServingRuntime, error)
	Update(ctx context.Context, clusterServingRuntime *v1beta1.ClusterServingRuntime, opts v1.UpdateOptions) (*v1beta1.ClusterServingRuntime, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterServingRuntime *v1beta1.ClusterServingRuntime, opts v1.UpdateOptions) (*v1beta1.ClusterServingRuntime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ClusterServingRuntime, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ClusterServingRuntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterServingRuntime, err error)
	ClusterServingRuntimeExpansion
}

// clusterServingRuntimes implements ClusterServingRuntimeInterface
type clusterServingRuntimes struct {
	*gentype.ClientWithList[*v1beta1.ClusterServingRuntime, *v1beta1.ClusterServingRuntimeList]
}

// newClusterServingRuntimes returns a ClusterServingRuntimes
func newClusterServingRuntimes(c *OmeV1beta1Client) *clusterServingRuntimes {
	return &clusterServingRuntimes{
		gentype.NewClientWithList[*v1beta1.ClusterServingRuntime, *v1beta1.ClusterServingRuntimeList](
			"clusterservingruntimes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.ClusterServingRuntime { return &v1beta1.ClusterServingRuntime{} },
			func() *v1beta1.ClusterServingRuntimeList { return &v1beta1.ClusterServingRuntimeList{} }),
	}
}
