// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/sgl-project/sgl-ome/pkg/apis/ome/v1beta1"
	scheme "github.com/sgl-project/sgl-ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DedicatedAIClustersGetter has a method to return a DedicatedAIClusterInterface.
// A group's client should implement this interface.
type DedicatedAIClustersGetter interface {
	DedicatedAIClusters() DedicatedAIClusterInterface
}

// DedicatedAIClusterInterface has methods to work with DedicatedAICluster resources.
type DedicatedAIClusterInterface interface {
	Create(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.CreateOptions) (*v1beta1.DedicatedAICluster, error)
	Update(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.UpdateOptions) (*v1beta1.DedicatedAICluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dedicatedAICluster *v1beta1.DedicatedAICluster, opts v1.UpdateOptions) (*v1beta1.DedicatedAICluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.DedicatedAICluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.DedicatedAIClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.DedicatedAICluster, err error)
	DedicatedAIClusterExpansion
}

// dedicatedAIClusters implements DedicatedAIClusterInterface
type dedicatedAIClusters struct {
	*gentype.ClientWithList[*v1beta1.DedicatedAICluster, *v1beta1.DedicatedAIClusterList]
}

// newDedicatedAIClusters returns a DedicatedAIClusters
func newDedicatedAIClusters(c *OmeV1beta1Client) *dedicatedAIClusters {
	return &dedicatedAIClusters{
		gentype.NewClientWithList[*v1beta1.DedicatedAICluster, *v1beta1.DedicatedAIClusterList](
			"dedicatedaiclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.DedicatedAICluster { return &v1beta1.DedicatedAICluster{} },
			func() *v1beta1.DedicatedAIClusterList { return &v1beta1.DedicatedAIClusterList{} }),
	}
}
