// Code generated by client-gen. DO NOT EDIT.

package v1beta1

type AcceleratorClassExpansion interface{}

type BaseModelExpansion interface{}

type BenchmarkJobExpansion interface{}

type ClusterBaseModelExpansion interface{}

type ClusterServingRuntimeExpansion interface{}

type FineTunedWeightExpansion interface{}

type InferenceServiceExpansion interface{}

type KVCachePoolExpansion interface{}

type ServingRuntimeExpansion interface{}
