// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferenceGraphsGetter has a method to return a InferenceGraphInterface.
// A group's client should implement this interface.
type InferenceGraphsGetter interface {
	InferenceGraphs(namespace string) InferenceGraphInterface
}

// InferenceGraphInterface has methods to work with InferenceGraph resources.
type InferenceGraphInterface interface {
	Create(ctx context.Context, inferenceGraph *omev1beta1.InferenceGraph, opts v1.CreateOptions) (*omev1beta1.InferenceGraph, error)
	Update(ctx context.Context, inferenceGraph *omev1beta1.InferenceGraph, opts v1.UpdateOptions) (*omev1beta1.InferenceGraph, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferenceGraph *omev1beta1.InferenceGraph, opts v1.UpdateOptions) (*omev1beta1.InferenceGraph, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*omev1beta1.InferenceGraph, error)
	List(ctx context.Context, opts v1.ListOptions) (*omev1beta1.InferenceGraphList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *omev1beta1.InferenceGraph, err error)
	InferenceGraphExpansion
}

// inferenceGraphs implements InferenceGraphInterface
type inferenceGraphs struct {
	*gentype.ClientWithList[*omev1beta1.InferenceGraph, *omev1beta1.InferenceGraphList]
}

// newInferenceGraphs returns a InferenceGraphs
func newInferenceGraphs(c *OmeV1beta1Client, namespace string) *inferenceGraphs {
	return &inferenceGraphs{
		gentype.NewClientWithList[*omev1beta1.InferenceGraph, *omev1beta1.InferenceGraphList](
			"inferencegraphs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *omev1beta1.InferenceGraph { return &omev1beta1.InferenceGraph{} },
			func() *omev1beta1.InferenceGraphList { return &omev1beta1.InferenceGraphList{} },
		),
	}
}
