// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OciCachesGetter has a method to return a OciCacheInterface.
// A group's client should implement this interface.
type OciCachesGetter interface {
	OciCaches(namespace string) OciCacheInterface
}

// OciCacheInterface has methods to work with OciCache resources.
type OciCacheInterface interface {
	Create(ctx context.Context, ociCache *v1beta1.OciCache, opts v1.CreateOptions) (*v1beta1.OciCache, error)
	Update(ctx context.Context, ociCache *v1beta1.OciCache, opts v1.UpdateOptions) (*v1beta1.OciCache, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ociCache *v1beta1.OciCache, opts v1.UpdateOptions) (*v1beta1.OciCache, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.OciCache, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.OciCacheList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.OciCache, err error)
	OciCacheExpansion
}

// ociCaches implements OciCacheInterface
type ociCaches struct {
	*gentype.ClientWithList[*v1beta1.OciCache, *v1beta1.OciCacheList]
}

// newOciCaches returns a OciCaches
func newOciCaches(c *OmeV1beta1Client, namespace string) *ociCaches {
	return &ociCaches{
		gentype.NewClientWithList[*v1beta1.OciCache, *v1beta1.OciCacheList](
			"ocicaches",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.OciCache { return &v1beta1.OciCache{} },
			func() *v1beta1.OciCacheList { return &v1beta1.OciCacheList{} }),
	}
}
