// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OciRedisClustersGetter has a method to return a OciRedisClusterInterface.
// A group's client should implement this interface.
type OciRedisClustersGetter interface {
	OciRedisClusters(namespace string) OciRedisClusterInterface
}

// OciRedisClusterInterface has methods to work with OciRedisCluster resources.
type OciRedisClusterInterface interface {
	Create(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.CreateOptions) (*v1beta1.OciRedisCluster, error)
	Update(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.UpdateOptions) (*v1beta1.OciRedisCluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ociRedisCluster *v1beta1.OciRedisCluster, opts v1.UpdateOptions) (*v1beta1.OciRedisCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.OciRedisCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.OciRedisClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.OciRedisCluster, err error)
	OciRedisClusterExpansion
}

// ociRedisClusters implements OciRedisClusterInterface
type ociRedisClusters struct {
	*gentype.ClientWithList[*v1beta1.OciRedisCluster, *v1beta1.OciRedisClusterList]
}

// newOciRedisClusters returns a OciRedisClusters
func newOciRedisClusters(c *OmeV1beta1Client, namespace string) *ociRedisClusters {
	return &ociRedisClusters{
		gentype.NewClientWithList[*v1beta1.OciRedisCluster, *v1beta1.OciRedisClusterList](
			"ociredisclusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.OciRedisCluster { return &v1beta1.OciRedisCluster{} },
			func() *v1beta1.OciRedisClusterList { return &v1beta1.OciRedisClusterList{} }),
	}
}
