// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	omev1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OrganizationsGetter has a method to return a OrganizationInterface.
// A group's client should implement this interface.
type OrganizationsGetter interface {
	Organizations() OrganizationInterface
}

// OrganizationInterface has methods to work with Organization resources.
type OrganizationInterface interface {
	Create(ctx context.Context, organization *omev1beta1.Organization, opts v1.CreateOptions) (*omev1beta1.Organization, error)
	Update(ctx context.Context, organization *omev1beta1.Organization, opts v1.UpdateOptions) (*omev1beta1.Organization, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, organization *omev1beta1.Organization, opts v1.UpdateOptions) (*omev1beta1.Organization, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*omev1beta1.Organization, error)
	List(ctx context.Context, opts v1.ListOptions) (*omev1beta1.OrganizationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *omev1beta1.Organization, err error)
	OrganizationExpansion
}

// organizations implements OrganizationInterface
type organizations struct {
	*gentype.ClientWithList[*omev1beta1.Organization, *omev1beta1.OrganizationList]
}

// newOrganizations returns a Organizations
func newOrganizations(c *OmeV1beta1Client) *organizations {
	return &organizations{
		gentype.NewClientWithList[*omev1beta1.Organization, *omev1beta1.OrganizationList](
			"organizations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *omev1beta1.Organization { return &omev1beta1.Organization{} },
			func() *omev1beta1.OrganizationList { return &omev1beta1.OrganizationList{} },
		),
	}
}
