// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RateLimitsGetter has a method to return a RateLimitInterface.
// A group's client should implement this interface.
type RateLimitsGetter interface {
	RateLimits(namespace string) RateLimitInterface
}

// RateLimitInterface has methods to work with RateLimit resources.
type RateLimitInterface interface {
	Create(ctx context.Context, rateLimit *v1beta1.RateLimit, opts v1.CreateOptions) (*v1beta1.RateLimit, error)
	Update(ctx context.Context, rateLimit *v1beta1.RateLimit, opts v1.UpdateOptions) (*v1beta1.RateLimit, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rateLimit *v1beta1.RateLimit, opts v1.UpdateOptions) (*v1beta1.RateLimit, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.RateLimit, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.RateLimitList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.RateLimit, err error)
	RateLimitExpansion
}

// rateLimits implements RateLimitInterface
type rateLimits struct {
	*gentype.ClientWithList[*v1beta1.RateLimit, *v1beta1.RateLimitList]
}

// newRateLimits returns a RateLimits
func newRateLimits(c *OmeV1beta1Client, namespace string) *rateLimits {
	return &rateLimits{
		gentype.NewClientWithList[*v1beta1.RateLimit, *v1beta1.RateLimitList](
			"ratelimits",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.RateLimit { return &v1beta1.RateLimit{} },
			func() *v1beta1.RateLimitList { return &v1beta1.RateLimitList{} }),
	}
}
