// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/apis/ome/v1beta1"
	scheme "bitbucket.oci.oraclecorp.com/genaicore/ome/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UsersGetter has a method to return a UserInterface.
// A group's client should implement this interface.
type UsersGetter interface {
	Users() UserInterface
}

// UserInterface has methods to work with User resources.
type UserInterface interface {
	Create(ctx context.Context, user *v1beta1.User, opts v1.CreateOptions) (*v1beta1.User, error)
	Update(ctx context.Context, user *v1beta1.User, opts v1.UpdateOptions) (*v1beta1.User, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, user *v1beta1.User, opts v1.UpdateOptions) (*v1beta1.User, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.User, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.UserList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.User, err error)
	UserExpansion
}

// users implements UserInterface
type users struct {
	*gentype.ClientWithList[*v1beta1.User, *v1beta1.UserList]
}

// newUsers returns a Users
func newUsers(c *OmeV1beta1Client) *users {
	return &users{
		gentype.NewClientWithList[*v1beta1.User, *v1beta1.UserList](
			"users",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1beta1.User { return &v1beta1.User{} },
			func() *v1beta1.UserList { return &v1beta1.UserList{} }),
	}
}
