apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-vl-4b-instruct
  namespace: qwen
spec:
  model:
    name: qwen3-vl-4b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  router:
    minReplicas: 1
    maxReplicas: 1
