apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3-4b-instruct-2507-fp8
  namespace: qwen
spec:
  model:
    name: qwen3-4b-instruct-2507-fp8
  engine:
    minReplicas: 1
    maxReplicas: 1
