---
apiVersion: v1
kind: Namespace
metadata:
  name: qwen3guard-gen-8b
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: qwen3guard-gen-8b
  namespace: qwen3guard-gen-8b
spec:
  model:
    name: qwen3guard-gen-8b
  engine:
    minReplicas: 1
    maxReplicas: 1
