apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "download-agent.fullname" . }}
  labels:
    {{- include "download-agent.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "download-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: download-agent
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["/download-agent", "download-agent", "-c", "/configs/partner-download-agent.yaml"]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "download-agent.fullname" . }}
          volumeMounts:
            - mountPath: /opt/model/store/
              name: model-temp-store
      restartPolicy: OnFailure
      volumes:
        - name: model-temp-store
          emptyDir:
            medium: Memory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
