apiVersion: ome.io/v1beta1
kind: ClusterServingRuntime
metadata:
  name: vllm-qwen-35-tp8
spec:
  disabled: false
  supportedModelFormats:
    - modelFramework:
        name: transformers
        version: "4.57.0.dev0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      autoSelect: true
      modelArchitecture: Qwen3_5ForConditionalGeneration
      version: "1.0.0"
      priority: 1
    - modelFramework:
        name: transformers
        version: "4.57.0.dev0"
      modelFormat:
        name: safetensors
        version: "1.0.0"
      autoSelect: true
      modelArchitecture: Qwen3_5MoeForConditionalGeneration
      version: "1.0.0"
      priority: 1
  modelSizeRange:
    min: 357.3B
    max: 436.7B
  protocolVersions:
    - openAI
  engineConfig:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
    labels:
      logging-forward: enabled
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values:
                    - BM.GPU.H200.8
                    - BM.GPU.H200-NC.8
    runner:
      name: ome-container
      image: fra.ocir.io/idqj093njucb/smg:1.3.3-vllm-v0.18.0
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      command:
        - /bin/bash
        - '-lc'
        - --
      args:
        - |
          smg serve \
          --host 0.0.0.0 \
          --model $(MODEL_PATH) \
          --port 8080 \
          --tensor-parallel-size 8 \
          --served-model-name vllm-model \
          --limit-mm-per-prompt '{"video": {"count": 1}, "image": {"count": 10}}' \
          --generation-config vllm \
          --optimization-level 3 \
          --router-tool-call-parser qwen_coder \
          --router-reasoning-parser qwen3_thinking \
          --backend vllm \
          --router-log-json \
          --worker-startup-timeout 600 \
          --router-max-concurrent-requests 512 \
          --router-request-id-headers "opc-request-id"
      env:
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      resources:
        requests:
          cpu: 128
          memory: 512Gi
          nvidia.com/gpu: 8
        limits:
          cpu: 128
          memory: 512Gi
          nvidia.com/gpu: 8

      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 90
        timeoutSeconds: 20

      livenessProbe:
        httpGet:
          path: /readiness
          port: 8080
        failureThreshold: 5
        successThreshold: 1
        periodSeconds: 60
        timeoutSeconds: 60

      startupProbe:
        httpGet:
          path: /health
          port: 8080
        failureThreshold: 300  # takes longer for larger models
        successThreshold: 1
        periodSeconds: 6
        initialDelaySeconds: 60
        timeoutSeconds: 30
