apiVersion: ome.io/v1beta1
kind: TrainingJob
metadata:
  name: "ft-llama-3-3-70b-instruct"
  namespace: "dac-training-test"
spec:
  runtimeRef:
    name: llama-3-3-70b-instruct-ft
  trainer:
    image: us-chicago-1.ocir.io/idqj093njucb/ocasgs-peft:0.1.15
  modelConfig:
    inputModel: llama-3-3-70b-instruct-ft
  datasets:
    storageUri: oci://n/id2imsfqczrq/b/genai-test/o/sales_pitch_generation_train.jsonl
  hyperparameterConfig:
    method: "bayes"
    metric:
      name: test-metric
      goal: maximize
    parameters:
      {
        "trainingBatchSize": 16,
        "totalTrainingEpochs": 1,
        "earlyStoppingPatience": 6,
        "earlyStoppingThreshold": "0.01",
        "learningRate": "0.01",
        "logModelMetricsIntervalInSteps": 10,
        "loraR": 8,
        "loraAlpha": 32,
        "loraDropout": "0.1"
      }