apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hf-download-agent.fullname" . }}
  labels:
    {{- include "hf-download-agent.labels" . | nindent 4 }}
data:
  MODEL_NAME: "{{ .Values.containerEnv.modelName }}"
  INTERNAL_MODEL_NAME: "{{ .Values.containerEnv.internalModelName }}"
  DOWNLOAD_COMMIT: "{{ .Values.containerEnv.downloadCommit }}"
  AUTH_TYPE: "{{ .Values.containerEnv.authType }}"
  HF_TOKEN: "{{ .Values.containerEnv.hfToken }}"
  OBJECT_BUCKET_NAME: "{{ .Values.containerEnv.objectBucketName }}"
  OBJECT_NAMESPACE: "{{ .Values.containerEnv.objectNamespace }}"
  OBJECT_COMPARTMENT_ID: "{{ .Values.containerEnv.objectCompartmentId }}"
  REGION: "{{ .Values.containerEnv.region }}"
  REGION_OVERRIDE: "{{ .Values.containerEnv.regionOverride }}"